apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog-webhook
  namespace: deploy
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ego-deploy
  source:
    repoURL: https://github.com/starburstdata/stargate.git
    targetRevision: TEST_SHA
    path: charts/datadog-webhook
    helm:
      parameters:
        - name: imageTag
          value: TEST_TAG
      valueFiles:
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/datadog-webhook/dev/_base/values.yml?uniq=0F0380BE-2B8A-49D0-8463-4B2A6F985165
  destination:
    name: control-plane
    namespace: datadog-webhook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
