set -euo pipefail

CONTAINER_NAME=${1}

docker run -it --rm \
  -e BRANCH_NAME="${BRANCH_NAME}" \
  -e COMMIT_MESSAGE="${COMMIT_MESSAGE}" \
  -e GITHUB_USER_NAME="${GITHUB_USER_NAME}" \
  -e GITHUB_USER_EMAIL="${GITHUB_USER_EMAIL}" \
  -e GITHUB_REPOSITORY_OWNER="${GITHUB_REPOSITORY_OWNER}" \
  -e GITHUB_REPOSITORY="${GITHUB_REPOSITORY}" \
  -e GITHUB_TOKEN="${GITHUB_TOKEN}" \
  -v "${GITHUB_WORKSPACE}:/mnt" \
  ${CONTAINER_NAME}
