apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: query-history-db-loader
    namespace: deploy
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    project: ego-deploy
    source:
        repoURL: https://github.com/starburstdata/stargate.git
        targetRevision: TEST_SHA
        path: charts/query-history-db-loader
        helm:
            parameters:
                - name: imageTag
                  value: ENC[AES256_GCM,data:cRkMwDEq1Sc=,iv:amP6SGLu5lERcrJAvaRYO7175uGjwtPuEhkhlFQ+4yo=,tag:1yda04Fqzp8NbT6kUhNKyw==,type:str]
                - name: stargateDb.baseUrl
                  value: ENC[AES256_GCM,data:7B4aePjtRRps+YJpW/EMbQ3Nns8vxqNudwk96mWDHJTCMPfd0xw6/WnvhgAlTRhXk8Fs69X70bGaAy1HkhNWHmt6TTT4LRA/wxtD1/lOgr0yEw==,iv:Q5MNbTpPTjaeNgKnpVqhcu55xVEGsDeU7a0W8e3e22E=,tag:bucNvXtYzetv9D2kKcMbpA==,type:str]
                - name: stargateDb.database
                  value: ENC[AES256_GCM,data:Z1QqzOVx8AdaqA==,iv:NR92xUYq87krXMNEzZc7ZcZaAEGOTgmDHCpgt1JILLM=,tag:RyUHgkYHk8/LdepGK+to7g==,type:str]
                - name: stargateDb.username
                  value: ENC[AES256_GCM,data:ElP/8fJZZzdtBQ==,iv:HWd7ZJe9/YSzZEQz39M5QexX6E/Wv/ygIPyYENhV7Nw=,tag:uwR4eyQDXMWDfMKB63pF/A==,type:str]
                - name: stargateDb.password
                  value: ENC[AES256_GCM,data:q8vgzVlDpgh3Z21D7Fgnvg25dZVKoRmo1e7ltGjD,iv:DsCp6QuGPc2VRQveEnk2no9PALrhIs+Zp2EfS1CSjTM=,tag:bYEJ4Dg0/ZW/3IGLhH4xPg==,type:str]
                - name: stargateDb.sslMode
                  value: ENC[AES256_GCM,data:8Qmr1Zau3A==,iv:I6T5hOnFmhDQ/1EmUUa6xfnBhDq4f/MtRYNHWFkHsHI=,tag:wQkHVJNsjcvKT18SgmhMrg==,type:str]
                - name: imagePullSecret
                  value: ENC[AES256_GCM,data:mAl53hmJ,iv:fe3vudRb9iYuumFbPCo+BiQ0ogq3nX6PhF04zlcsDOw=,tag:F1cEWSOi88qj5pUgXqJl0w==,type:str]
                - name: localDevelopment
                  value: ENC[AES256_GCM,data:ewwnO1U=,iv:sKGNrO5Jy9I6/i23ES6tTyP8U7Cge+LW8KSRqve5xDk=,tag:aIIcoSeazWaUb6uw0vnnDA==,type:str]
                - name: kafka.bootstrap.servers
                  value: ENC[AES256_GCM,data:3DMtQmdWQmA8t3fh9pacVerXCRgEn81g5FtNdi1UO1X0Vmf+sHlCMusLd9M=,iv:C1YS7GUQdIgMkzSdrPIQbdrMjzpl+WR/k8yMj+oPMnU=,tag:bfPeL/qzN8PSo5iMA7SKag==,type:str]
                - name: kafka.sasl.username
                  value: ENC[AES256_GCM,data:OhxLceABEUr7ko+vlPxhkQ==,iv:zb6KMg0fBcCIvYcgJTXeGenJ69mbNi9uTrStNvPjVAg=,tag:FFCmeyjYmGO0OK5o/vy6Vw==,type:str]
                - name: kafka.sasl.password
                  value: ENC[AES256_GCM,data:gAe7jvAkH5S5S9LE/7Nt3wdwwm4CqOuOBvHzD/Do9mQITDLQ0PgHO0GVFdRCWop0QV21b78Tm8oEId9O67W6zA==,iv:arD9BN+9EaNXyrWRY0PAx5cy9dAOwTomWdqn6sTF5OQ=,tag:qzspghHTCLAjmmC52xm30Q==,type:str]
                - name: dockerRegistrySecretEnabled
                  value: ENC[AES256_GCM,data:lBE3Bnc=,iv:w5JhNt1nPn5tD1qC4KPpJKk1qCvgYf3Et/Uk+gr4B/E=,tag:GwnmCDpNGj/q9xn+Jfxcmw==,type:str]
            valueFiles:
                - ./values.yaml
    destination:
        name: control-plane
        namespace: query-history-db-loader
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:662260526581:key/3f226811-712c-49d1-a5b7-de59223ec1cb
          created_at: "2022-07-15T14:34:46Z"
          enc: AQICAHg1QZDATeVp971NNJF8tQQgf93gP0h0ctR/hGudQ4wAMQEEMvPGvrQAUr3sIZl5GWr/AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMEcmMphe1s4rDDBXnAgEQgDuUWq+vXJNb37fOy2C5ghYOM3G1YUZrcMbRkEYw0qn/SiDGWzpxOcv/diB3TuF6j6C7gh8yKaKZzO27Gg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-15T14:34:47Z"
    mac: ENC[AES256_GCM,data:ELLooMFannOhDmTvcioSb5d+UIbBIQaBPHiPat99BpnX6AqflkbQpT8+MIuq5Fu0ssH5VArfXtF1Fsyngh1BK3MEawPuTmIWfGWqfk19jCKgr3MEXd6XaIUC0Q1UjPm4TPKk88sumuZJJvFZb5GgCngDrwL+W1PEV39wFwHvsPA=,iv:7HcdRuFVHnFkdhRhD5Nj/IqnXx9lL5czid3CVBHfTec=,tag:+JO47Y8aGrLQqQFc6HYypQ==,type:str]
    pgp: []
    encrypted_regex: ^(value)$
    version: 3.7.1
