apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: query-history-db-loader
    namespace: deploy
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    project: ego-deploy
    source:
        repoURL: https://github.com/starburstdata/stargate.git
        targetRevision: TEST_SHA
        path: charts/query-history-db-loader
        helm:
            parameters:
                - name: imageTag
                  value: ENC[AES256_GCM,data:6nQzFWy6Ajs=,iv:PfCXg04GBpBQZsZM5bX1e0+drtWBOwNJyjJCM8dYNng=,tag:dn4ImdO7c8mtkKOvYc+aJA==,type:str]
                - name: stargateDb.baseUrl
                  value: ENC[AES256_GCM,data:rN9GUrcs3rmPYUA3zIroAN51vZAS5rQyhyIbOUUV3lx3nlijO9V8uiHtV4lVsgy+yflaJPI0qTTgC8epuUsRSqBZXnmG0Cvz1Ysbxeg9xxsd6w==,iv:s+4PogFIThugixJ6YrdDm9BrP6OaDcqkZJAP/TOE3Ss=,tag:DgLQDZ8o7TfTkUTZ4bFldw==,type:str]
                - name: stargateDb.database
                  value: ENC[AES256_GCM,data:lzoObtgj1K2TkA==,iv:UvW2CvY0fin3G6xpWLjtrbfdamD+aU4eiyah3lQDmlM=,tag:IiM0UvKomIsWjRXVm16Hqw==,type:str]
                - name: stargateDb.username
                  value: ENC[AES256_GCM,data:U77NEF6BVaTTTA==,iv:YugVa3uQuo98MUwlxJiFxohUFsb7TNzLr9mcEumsMbA=,tag:Kb9YG8cwSTjSK+LWRSz7kQ==,type:str]
                - name: stargateDb.password
                  value: ENC[AES256_GCM,data:yKXlTULoNNgsULkoC4wTjkituIVEHqh2qLkaJhTK,iv:OgHY+Slx2MnzZAXiRoTDUYgQHWHvvBZZYgu81z94eVk=,tag:VeX8Q4c24j+J+armRTX6QQ==,type:str]
                - name: stargateDb.sslMode
                  value: ENC[AES256_GCM,data:GMp3PiQ76g==,iv:XXUbC6p+z9l84Uno2YqU8g0Vjx//BNfM5mptqwGd3jU=,tag:xqu1l6OYTB2OhkiwOjNyAA==,type:str]
                - name: imagePullSecret
                  value: ENC[AES256_GCM,data:CZvdfGmU,iv:NAxOlOzEtWRxBgQwmxi/ywZKi3UQETwVvNaTXwE3Db4=,tag:JPVIuAck660M95OOkI7DVw==,type:str]
                - name: localDevelopment
                  value: ENC[AES256_GCM,data:cehjgnw=,iv:mneXldAzBe0FsPvtJKVM0MQQDIbt2V7CNSwkgWcOT70=,tag:k86htBsd69WxBukkb3vcsw==,type:str]
                - name: kafka.bootstrap.servers
                  value: ENC[AES256_GCM,data:Qs2NNTSt2cJbnAtkX3Xd/AnIeeEJJ3mLM5VSHQA5/BzHuhMUtdLe+Xw67UA=,iv:gDEXcXv9Hc32qkO6bHLoNN4mS8bnEcNljfj+S7IDM+A=,tag:Wv/TZ3zMuo9nFLTdtWp0fw==,type:str]
                - name: kafka.sasl.username
                  value: ENC[AES256_GCM,data:YvXyo+XYq0JyW1AmjeBaOA==,iv:Db/TWOuqx7uxtNfPMdxTMQT4gP95NUjJcSnzao7jxDY=,tag:879QQE7MDSwTxt8Ff5e1xQ==,type:str]
                - name: kafka.sasl.password
                  value: ENC[AES256_GCM,data:oNenH8lsP8ysJfftro9cTUs83MpZierPYHcyYMWL7varEWZnDEdhedWpYMjJim6BckTMYGDFiR/Dg/bg5ccobw==,iv:htbCoirE7Ry267LOjCoqb7zI0cl+SRMaIcRBvpKWPoc=,tag:HLknvJAV6y4FQk7ZRaLFxw==,type:str]
                - name: dockerRegistrySecretEnabled
                  value: ENC[AES256_GCM,data:hBnqfsc=,iv:cS/6f4wCeaijv+bnGtx99bb3r/dNH/oahiO3hS+GO0Y=,tag:QCDra2JHwZgCOA42dO24jw==,type:str]
            valueFiles:
                - ./values.yaml
    destination:
        name: control-plane
        namespace: query-history-db-loader
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:662260526581:key/3f226811-712c-49d1-a5b7-de59223ec1cb
          created_at: "2022-07-15T15:12:10Z"
          enc: AQICAHg1QZDATeVp971NNJF8tQQgf93gP0h0ctR/hGudQ4wAMQHAddO8H2dDdADrXoBJX+eNAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMRp0knfd4gCYBx5naAgEQgDtESGVZ7Ma0Mqc+85tRAxhE6aUCdS45vmYzRivHFqE6UX58mPR9F92MZxBH0DEvgs2veVKZUQPciZT42Q==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-15T15:12:10Z"
    mac: ENC[AES256_GCM,data:TxknqMBU76iFMnFQKqLQulOFNZAs1CKq6c0I53bEe4ZE1UwI1Gi29cQ1NDkkwDqhANl3ouaQrgTNR8EaYFEdsMJoVL2ZLznb4tu8uc+SecuKdsvskBl1Sk+1+x8EQtsC07VlRT8ksXtqSYo+R1DWme55mfe3XiSx3A6KmXDHnJg=,iv:PE/jGgHboTjF81uujE9Su6lGgvhjl7D9Y4pc7Y5KU/A=,tag:/J1jCNmOKOfPWuh2oMtrdw==,type:str]
    pgp: []
    encrypted_regex: ^(value)$
    version: 3.7.1
