apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: query-history-db-loader
    namespace: deploy
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    project: ego-deploy
    source:
        repoURL: https://github.com/starburstdata/stargate.git
        targetRevision: TEST_SHA
        path: charts/query-history-db-loader
        helm:
            parameters:
                - name: imageTag
                  value: ENC[AES256_GCM,data:gfnsx8GxWG8=,iv:MsEr+2toqOsiqv4brcaBw3ACHTAVY7HCt/Bpbhzk/9E=,tag:xsex6xFOlA15WpO2zCezUQ==,type:str]
                - name: stargateDb.baseUrl
                  value: ENC[AES256_GCM,data:aTyTBr5ygVSkiA6fKLqilwdFOwKBNPUHZFX8YnAQz9CQ6vpoz7AQiCQn9AUZCnXT/mlUG4kDnsb8AU1PXc83geyYuBp9VNOoMjsRcpG+gLndhw==,iv:EEp2h4PQ4TWK+TGPiZrThd3m2iD8+uG2GfZkBcm2ZIE=,tag:ofxW4QFqw9idFfIYH0BXgw==,type:str]
                - name: stargateDb.database
                  value: ENC[AES256_GCM,data:xa2LLbEPARvugg==,iv:J0TVoojxkd7Sy6alGedncNSacqiriOrgABFbCX+c23Y=,tag:ZYb3aBEZY7yG1Bt6VsUzcg==,type:str]
                - name: stargateDb.username
                  value: ENC[AES256_GCM,data:OonjaU7pw2rNMw==,iv:iQFt9ny+2rn5HtarlXl2vyVAb3LWSyyK6VisGXNA3/s=,tag:q7F80BIkePNJtbwXHen3mw==,type:str]
                - name: stargateDb.password
                  value: ENC[AES256_GCM,data:9vI0jF6KDOJEDwChThRSHdN0HKiDVkOQ/al+/4/w,iv:EoDlZUGWmzRWJci9tkuHfkYZySMjBAUHZzsUJlaR13g=,tag:2I5XMKHBOw7fC+KTpMxZAA==,type:str]
                - name: stargateDb.sslMode
                  value: ENC[AES256_GCM,data:2NcErimDTA==,iv:i5ik5J4R8VEK9yAVl1Ex9m25Y7XCt8HNJiTtaRwzdug=,tag:xrZeBOsqsAvNS0GucNR0yA==,type:str]
                - name: imagePullSecret
                  value: ENC[AES256_GCM,data:0H5YY0u5,iv:jTgs+w6pDz/pBNT9YMLuqyFRahoXfvOKZ1K7XAM/XBk=,tag:MEGhvmjYXxQkDhEgsWdTHw==,type:str]
                - name: localDevelopment
                  value: ENC[AES256_GCM,data:bo0mlfQ=,iv:ZSnvkavc0qo+j4FfYedaUdljtoBn7CGLLQJLCn7m4uc=,tag:3aA8BEPeji59MJU+nz01BQ==,type:str]
                - name: kafka.bootstrap.servers
                  value: ENC[AES256_GCM,data:DhO1kq1EoEoy9eI1VCiWHuPaycSqXddV+jhzxbF0CI5x3R1rwTdo3RWiuYU=,iv:EiP8PjX7Hr00/LrppJgh8EbNT2QqvYw69K2NwOWu1Ns=,tag:lhdd4+ZvAQ40LU3ITsBMGw==,type:str]
                - name: kafka.sasl.username
                  value: ENC[AES256_GCM,data:Bvql8SI7JwGxqBQMU+9vKA==,iv:FtZbACrXjFV3LR0XvaPW57SoNv3QW7A6MURbdVNFt+E=,tag:FES9LM8F2SOmwtfs/5QR5A==,type:str]
                - name: kafka.sasl.password
                  value: ENC[AES256_GCM,data:tQhuyYiqBljb98i+TMYnlaTdP4nzSKEz8xPO169pot7n2I1PivrQWuK4E+sm+3uaL5FOriU2J8QJwoRSHvsmnQ==,iv:iT+WT1aKXR3onIBN0EhX6MN6OCgWz0cAXriSzVPf6VM=,tag:+LIE3YMXxmQ2Yei5uonS/g==,type:str]
                - name: dockerRegistrySecretEnabled
                  value: ENC[AES256_GCM,data:cb8aZyo=,iv:uXCjqGCeyJcxHAxAc4A++87AGUlFdNDm8aXIwFX7bIM=,tag:caaATtRy+EoWshXhP0XVDA==,type:str]
            valueFiles:
                - ./values.yaml
    destination:
        name: control-plane
        namespace: query-history-db-loader
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:662260526581:key/3f226811-712c-49d1-a5b7-de59223ec1cb
          created_at: "2022-07-15T14:55:36Z"
          enc: AQICAHg1QZDATeVp971NNJF8tQQgf93gP0h0ctR/hGudQ4wAMQF0m/X5a2VwQKHjyDQHl8jeAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM2R8JHedRH4nVTxwsAgEQgDsb6AZwy/e+1j2p2iXKDgNai5bFJy98iKWDXTgb3bqQqcbGXg5MZBNRnIetD2cJ9wA0gIIsyVTgOKLqOg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-15T14:55:36Z"
    mac: ENC[AES256_GCM,data:vCond6i3NjdjJchMjLK6M7w1B9t6kJV3Z6k4uelzwOG2jkxiGaiRBiSECZpF92TQMYMIYKYS8X24WfRcrvNsGsHBNAKrgPfJQReOcGOLqZuGgMCXlPDNqOezY3ScwHhAg39YfqIGte5+It8tCKVtCxcieTBDao9BMITsmSqF/6Y=,iv:fp5AgEo75nfplRmsV5GioVJ5Eub+VgiyzJvdhc0BcvQ=,tag:Ac/urEBAspxnzIwzSWLgeg==,type:str]
    pgp: []
    encrypted_regex: ^(value)$
    version: 3.7.1
