apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: query-history-db-loader
    namespace: deploy
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    project: ego-deploy
    source:
        repoURL: https://github.com/starburstdata/stargate.git
        targetRevision: TEST_SHA
        path: charts/query-history-db-loader
        helm:
            parameters:
                - name: imageTag
                  value: ENC[AES256_GCM,data:LkNUJKGg5AE=,iv:fKAUvJ3MFs8NZajvemXb4ycFtw0TsyH5x5tjLFf94g4=,tag:W+q6843qiJilOLsyeUBPiQ==,type:str]
                - name: stargateDb.baseUrl
                  value: ENC[AES256_GCM,data:zH2XHDeWwuSDk5vFuU8U670YVzPdkpRF1Kaw/Vz9T7qDAJc1Fq/zMmua3MfW53fdS+d4dvYWe+65qLMOOBygePUYmjMk47g13YG4Yg+DkigZSA==,iv:+ieMY5UpK8gyFx7FSxY3jQD6GsXwEGFF/R9GFocnsBM=,tag:TGF7eNyVrvVAgMRC+WsLvw==,type:str]
                - name: stargateDb.database
                  value: ENC[AES256_GCM,data:1PI1+ENY/8MaZw==,iv:uPGQUQutG9knVkGYvmp4lLFX36EVCmh/HDbErA75o5w=,tag:wbLPCV+ig1vy+98ZEXkZLA==,type:str]
                - name: stargateDb.username
                  value: ENC[AES256_GCM,data:31gJdagPFtTd2Q==,iv:xL8JZYoPoUOB6V8ptF1JNXjYdamrxzVj1KD+OQJX60o=,tag:oV1+vnk2Irg58GurTK24Bw==,type:str]
                - name: stargateDb.password
                  value: ENC[AES256_GCM,data:TbnJehyWYSbwxiYUWQSjDEBYN+CyDUtBVVLy4eAh,iv:QwSZxhzyhESDlkwkgVbdTx9G9UMehUe9yGckro8CGxQ=,tag:zhs0xvg57M7EYFlP3xX/OA==,type:str]
                - name: stargateDb.sslMode
                  value: ENC[AES256_GCM,data:y2rnp+Wrgg==,iv:KXHEPO6jbtTXUxc0oGw5q/7Rpjmh3xLBi6ECh523zjk=,tag:9qwI3o/ajvbZMQS2+YeSZw==,type:str]
                - name: imagePullSecret
                  value: ENC[AES256_GCM,data:1HZrWWEt,iv:VTmG6dlNTwJ4RevJ307d0STUbTtT03EfKYp9v/yY9cA=,tag:fzVoJmT8N3fRcqVgedkz3g==,type:str]
                - name: localDevelopment
                  value: ENC[AES256_GCM,data:f/O6xF0=,iv:sYcKNM8jCo7XUnFOqq8Epiqg4wKxKeAQJrJ3B+PulNo=,tag:wDhDIdKQBBKWZeFQonNp7A==,type:str]
                - name: kafka.bootstrap.servers
                  value: ENC[AES256_GCM,data:T2ynNh5d0CNPyd0oeRPoch22Wr14eAwDy9/hJJ+lCX8d0x7V8bGQEbK5g1o=,iv:fE6AMhcw0f9RCfeq6LagdY/DKpMSWPlpMQxsRqoNhUs=,tag:6keVHja1TnJPCEzQ91kqUg==,type:str]
                - name: kafka.sasl.username
                  value: ENC[AES256_GCM,data:pSGXFzNIQPTc/Dy4LJc0+A==,iv:kUfydfvsqRZmfxTLADwT87Uz5P1B+jA3WTnT9lh8QpY=,tag:OuM+Xm00OgCQ1px4pm/HOg==,type:str]
                - name: kafka.sasl.password
                  value: ENC[AES256_GCM,data:1cDbd0uAwgFtGlgNtKVASbq9L28qB0RpcZDTdjK+WBDFwRTRyvWbO8mndgNTTEWRd1YCPlKC4fZg4JgTPZv4wg==,iv:x15VK45tiOPOrRguTf5W8zMfu/mzpyncmf7IBFeHzi8=,tag:vA7/W1E8Pc6U0dZJXmZTSg==,type:str]
                - name: dockerRegistrySecretEnabled
                  value: ENC[AES256_GCM,data:VIDZYcE=,iv:uPs0PvWEEENgg9SbC26lj9oPS2bRaO55VbMsL0w3DRo=,tag:Nr2zx1CsX3F9wTzR3njZFw==,type:str]
            valueFiles:
                - ./values.yaml
    destination:
        name: control-plane
        namespace: query-history-db-loader
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:662260526581:key/3f226811-712c-49d1-a5b7-de59223ec1cb
          created_at: "2022-07-15T14:26:57Z"
          enc: AQICAHg1QZDATeVp971NNJF8tQQgf93gP0h0ctR/hGudQ4wAMQF1w2UvDsj0RaXai2UMBpDeAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMzlxwI/6szYkI8fLNAgEQgDtO4/L67D058ZV35AHNjhkvKHBxcJYfZFtLirSXjfB+NzRpS0wWD0HUkxStaycCBjviO/pm+qTaGEVyMg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-15T14:26:57Z"
    mac: ENC[AES256_GCM,data:aKG77a5isfiYA8Moi2cEpQvWhEQV0XvkOhmjibioRzJH1VO8lNoe+MRTKRokUXmL3mFmZzzZ5q3WlTNpOcQylHASPMtIlkv1F+4O9u+rPlAgr15jJ97qcDok1TOwsGdYyCAf+KtZ4Gyai4XWBNwr8Xz6otsE7/eLMyRff+1BcCg=,iv:MY5REXmU3pv/OvUeln1OGOQl6PltK3SaQPEQ5B1Kdyg=,tag:p6HW4JpdHNAw5yw8JViOHw==,type:str]
    pgp: []
    encrypted_regex: ^(value)$
    version: 3.7.1
