apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: query-history-db-loader
    namespace: deploy
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    project: ego-deploy
    source:
        repoURL: https://github.com/starburstdata/stargate.git
        targetRevision: TEST_SHA
        path: charts/query-history-db-loader
        helm:
            parameters:
                - name: imageTag
                  value: ENC[AES256_GCM,data:bAQhqRQT0Ew=,iv:1BhMoj5bEhcOdrweHg2FZc0JftsQaMyhjEA1/gRQlec=,tag:V/VB7pXRRzmhhuTt+01sEw==,type:str]
                - name: stargateDb.baseUrl
                  value: ENC[AES256_GCM,data:JdQ5zVyytsrh0qw56fJeWB3Yqq+d/rCFmT05EuDwM13MOyDPQk9REPm/M8NPw52D38jBg12INLbf2Y4C5Y9uWfcB4r8Zy3nd8KfPFGrJKyMvHg==,iv:5xM8Wn9Fj3uGFkRv3eCN8y9/GXUABpraWwSfwNHHxsg=,tag:23EMDJWB7FkFcHMjvawwYA==,type:str]
                - name: stargateDb.database
                  value: ENC[AES256_GCM,data:dmVzSEAEoTZYaw==,iv:z+/5tLRiADM9FxcZS8A1JK5JNAyu2vwKhxZgkwSYElM=,tag:/WGK0I25eB9/8dhktsDmMg==,type:str]
                - name: stargateDb.username
                  value: ENC[AES256_GCM,data:whxZeleecvjCkA==,iv:r1TQJpyxhfphf52Hj/a6+XPHpe+rpZN9Geh88biy7jc=,tag:Ro12eDxukQQJW/9CzX4ZqA==,type:str]
                - name: stargateDb.password
                  value: ENC[AES256_GCM,data:sQ3WCf97enV2yUQf2NzeoiQGxPHaQutWQ7Ho8D/x,iv:8tgU1OhRTtD1V0SJZ3IEFy2Xi5i/yEHCRb3lDxw0VhA=,tag:fH5JgE6ZlbDzDY9mQyVmCQ==,type:str]
                - name: stargateDb.sslMode
                  value: ENC[AES256_GCM,data:QhdbjxhsPw==,iv:C4wefIGP+pTm696acjejhawBMwNqoWM9kSaoGsesED0=,tag:K4pY/cJgQK6319O/zqMvlQ==,type:str]
                - name: imagePullSecret
                  value: ENC[AES256_GCM,data:g0H/u3sZ,iv:UCQ5+Ul4Qn6HEkIfmMybTY0DtRkjx8+e4up9hXanwOk=,tag:kM5ODklwXGpd8MNRCNPfyg==,type:str]
                - name: localDevelopment
                  value: ENC[AES256_GCM,data:NBwBHDI=,iv:1EcU85ifn6cgl9KPaB/H+7twpcRCOvbPqDeAIxYwwAQ=,tag:EZ6OhGz2J/2CZHFs+yC6Hg==,type:str]
                - name: kafka.bootstrap.servers
                  value: ENC[AES256_GCM,data:NH9dMxmu2wNQvvIyu9XQYwj3wiCrkgyRZ1qiCIp/UE9c2yMjrlRENVnKBU8=,iv:ylyha9QLxuHbJGU8fsTOampiwMJ9zLpF0ZDb1wvKf9I=,tag:/UqMNSnkgvgyo9b5BNHawA==,type:str]
                - name: kafka.sasl.username
                  value: ENC[AES256_GCM,data:GwSdYmzTxv0KVT8kiQjW9w==,iv:sjQEuthbJNmftARj2JCqCIEba4gj3TwbQgCsan6PYOI=,tag:KRIVdLfuEDDBfnYydTyGZg==,type:str]
                - name: kafka.sasl.password
                  value: ENC[AES256_GCM,data:pMdD2LtL87SIRuQ2a2aJhdHDL8ZOkS62Vi6qEqz0kDBOi9KgaZapay22eoaKImTpFHPw0B11GYEr5Zjxy0N+gA==,iv:huEbjn0fUu20Mvjy+R522gxsbxaxG47jFovr4FCjkds=,tag:Kz9B9toGYdRLaCI/62jNBw==,type:str]
                - name: dockerRegistrySecretEnabled
                  value: ENC[AES256_GCM,data:ilUHVnY=,iv:T8OhyBL05EOz9yCbE1VwmJapHUh6TrdGObwojOdKux8=,tag:OpRnmYppMJHc1t3RYx1Vng==,type:str]
            valueFiles:
                - ./values.yaml
    destination:
        name: control-plane
        namespace: query-history-db-loader
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:662260526581:key/3f226811-712c-49d1-a5b7-de59223ec1cb
          created_at: "2022-07-14T21:39:43Z"
          enc: AQICAHg1QZDATeVp971NNJF8tQQgf93gP0h0ctR/hGudQ4wAMQE798lo8vsEILzXGtu9qtd3AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMO7CU6Y9IyQJL6xV0AgEQgDvlrrV42xhYPZYA8JZUz169hw6eEFFCgIYdB+gsCg1jzEbnKJ+L4Tc1ucvCKSXSNfjEnrbo32gJXBpDRQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-14T21:39:43Z"
    mac: ENC[AES256_GCM,data:49pYfy8U0J5EDd7cQe8QgeLwcFjYhCep+pCT3ntK8p2DgHnleEJYXtOoTCr5MkpEvJuIm/E11U0qWQX9nzGTvhOG5dyOpTz+MoJ9CyLEJmbk9TgjASiJ2TxnzsxxffNkVhU/pA0lxCOJmV84mPZFU1ZsA8G8sl7x9XES+54GTQ4=,iv:M1231IsOfaa+QiS2SRDTRb9dyAuhrejdA8s0IcE3zhk=,tag:geoA7IrJx4f0FfVU+6r2gQ==,type:str]
    pgp: []
    encrypted_regex: ^(value)$
    version: 3.7.1
