apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: query-history-db-loader
    namespace: deploy
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    project: ego-deploy
    source:
        repoURL: https://github.com/starburstdata/stargate.git
        targetRevision: TEST_SHA
        path: charts/query-history-db-loader
        helm:
            parameters:
                - name: imageTag
                  value: ENC[AES256_GCM,data:OVmmm0E4GwE=,iv:YmnOCUKXqLv0z0us3jB2hRkJUxhmkvm+Q7NvrCvL95A=,tag:ugtozZe0g6uX4SQ/OMB5pA==,type:str]
                - name: stargateDb.baseUrl
                  value: ENC[AES256_GCM,data:zIYWcAD5gpk90+kf2uj0/MBEVmW3K2eoUp4yU0kZtqQMdfAvKRPYU2vJZJfPiyBfiXQZzfJX2VmTtBTWiOs63Gvg/hqANzOTizZH12YeNVCvHA==,iv:ucpDtLBPD4Aogw8Dhi5fJEqanX0uG/lrcw6rwnd4ThA=,tag:qcZtMBRaSq8UU+jVo78ADQ==,type:str]
                - name: stargateDb.database
                  value: ENC[AES256_GCM,data:kdxzgeTkmUk8ow==,iv:zgIQ2qiNZg45iz1k8qa2sB3yV7FxdSuf31ARup6PqfI=,tag:Oyu+dmFrbLy8ICprAiroTA==,type:str]
                - name: stargateDb.username
                  value: ENC[AES256_GCM,data:dpt39KH2IMz5Wg==,iv:fcywyljGQnk9AdXfvcCRXINuTgpc7ysvL1noqQK6QCI=,tag:luyPocKZOOWg/hPRUaDoCw==,type:str]
                - name: stargateDb.password
                  value: ENC[AES256_GCM,data:u7xNANVYPqHpq+itT5F+4w1xICwvPrfmz98tMJqo,iv:Si6MRGH4JDY/F64TiDIvqlcK/R73mrR49tUhI/4y42c=,tag:B0wxJOFvCeqtyK0gzfW4LA==,type:str]
                - name: stargateDb.sslMode
                  value: ENC[AES256_GCM,data:CZAkMnpmpQ==,iv:44sYbsxLDLm5VywjwyqTgdKyCs6EEVNXvBsflzY7JeQ=,tag:ql5p4lvV5iGIkuMtUpVwSg==,type:str]
                - name: imagePullSecret
                  value: ENC[AES256_GCM,data:qP5WzvYv,iv:sItmOa5/fsi7vtkvV/9Zyek9FhkjHsVTKa/zdLVcp4g=,tag:zmbyXhUhOyXVQ0JbqS7qZg==,type:str]
                - name: localDevelopment
                  value: ENC[AES256_GCM,data:NZSdKBA=,iv:XCydLkswFyr1K+LgDLEaG9T9V/vzY7g0FvzWai537d0=,tag:/Ofi4a3dSydpdxiywa3Ojg==,type:str]
                - name: kafka.bootstrap.servers
                  value: ENC[AES256_GCM,data:Kri/i7KdQMBErILOO/2W1U/+R+l1SanvXDN81E1JhUqjnMsnoQzDqVhWSPk=,iv:fzWG8pp1SUBf1mDVO6w77DwuaS0RfkSTs+l5MTtPWgg=,tag:hR/cF4b+SL2VY7qNGMxgPw==,type:str]
                - name: kafka.sasl.username
                  value: ENC[AES256_GCM,data:SHBmPrWyoOFO3bMp/bR9sA==,iv:qFKktjCDMJmzZjjdEMedbyLpiVxEV4wr3dY7m6YKVmE=,tag:m4YHZgmxXjNskW4ObEp4Tg==,type:str]
                - name: kafka.sasl.password
                  value: ENC[AES256_GCM,data:Rd9M9R/S9CBWIXxvEJyIpyLJRNoeiK1PO9niII8DNbLNUd06YAIbxSHq0JAPeefB77dODN7hdSETbTnJTG3RkA==,iv:ooi3MTJ3J5xBxvQosvV7pExz54o781akC8bLkkLbeoc=,tag:hcefu0INZEoQIg4kIKeQKQ==,type:str]
                - name: dockerRegistrySecretEnabled
                  value: ENC[AES256_GCM,data:hGQ7nV8=,iv:BcAM4hu/kzHHZhwlRVWdIx1aaM+KinXqiPoW7hGhWmM=,tag:VuvuIudHhv6Yvv6gOOsakg==,type:str]
            valueFiles:
                - ./values.yaml
    destination:
        name: control-plane
        namespace: query-history-db-loader
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:662260526581:key/3f226811-712c-49d1-a5b7-de59223ec1cb
          created_at: "2022-07-15T15:03:18Z"
          enc: AQICAHg1QZDATeVp971NNJF8tQQgf93gP0h0ctR/hGudQ4wAMQFY3NSE7GUdilv9Hae5LD64AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMFm/VBAWP6Rsb4OdZAgEQgDsUi6n72NnzxDt0jNRohVrcQxeNigb4GXZis417TzYw2cjkjuiNHDANeZXRQBunItl/6I8pNa4tYwcKmA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-15T15:03:18Z"
    mac: ENC[AES256_GCM,data:WVamdX8HE/igZoDkxVaYqn8KmX01bXgK3V5BNi1aGuRDb8qolu/qTSNPRN8WALWFc6L2U59ynAQwXK4JpLHN0e3pseOanxX4ueU8368RLQBTxoCdlZF+KyGlxK7oWTO5NhQ+k9L2vZGbMy2wVgYpXQbIfYxfUrADXEwBgmcjNuI=,iv:SLTyVA36dR9hMEbpae44ysUwu0q13MY6ukJX3s7wHG0=,tag:YU6bIpWBUGnjktBfH15ppg==,type:str]
    pgp: []
    encrypted_regex: ^(value)$
    version: 3.7.1
