apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: query-history-db-loader
    namespace: deploy
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    project: ego-deploy
    source:
        repoURL: https://github.com/starburstdata/stargate.git
        targetRevision: TEST_SHA
        path: charts/query-history-db-loader
        helm:
            parameters:
                - name: imageTag
                  value: ENC[AES256_GCM,data:Gn2ikMWcgSI=,iv:VBQdyjUtTFR3xrkAOp5pQEbnFbTv56LT7N0Y/ozhBhE=,tag:Ei04Ja8aIeVk4fZSdGDBKA==,type:str]
                - name: stargateDb.baseUrl
                  value: ENC[AES256_GCM,data:9CLSBu3QE7p84KCxqHtWmtO9bdCh0l0vKR3ru4ilZHJ6kcEA2ni/Ar3qi2zG8Jc+CSV2pKwqxa6eLfzzerTVrmp7Pli1rZ5+el1j/cUYyCKq0g==,iv:WUuqh+u1OJlRda5dDHXkJXlfCDb4IN8rXYemZ1FM4rQ=,tag:UpCwWTA0TjQ5gi+5hx0Eew==,type:str]
                - name: stargateDb.database
                  value: ENC[AES256_GCM,data:LTZ73t9PhlZieg==,iv:XVYGJMzLe3RjiKwpg/5FxfWZgbzExjxw80EvbPVSRkM=,tag:M9aP/tugdcTdmm9i5PSfkg==,type:str]
                - name: stargateDb.username
                  value: ENC[AES256_GCM,data:jlBD5cavh8sLKw==,iv:VzEVPG24hS5qXeqdMJtIf8K7TJZ20DO1arhU+88dkUY=,tag:WHtPCytgzGVn9gLczI5Wzw==,type:str]
                - name: stargateDb.password
                  value: ENC[AES256_GCM,data:7lVuadzwNe52WH0fK8q3F2l/8b0Y7dOH3YQ0MWD/,iv:Hj9lIpOw4OA9tV6dVwwy3coUyIxTnIQoxO+/crjmDhQ=,tag:qna5MKx5CytpHvQPt9RRrw==,type:str]
                - name: stargateDb.sslMode
                  value: ENC[AES256_GCM,data:vKsH5Zbv+A==,iv:v3/DuqgFLgUI6tsEeDodc6+2+FkAn2URyjzKQk+qIQk=,tag:+M/I+sL5r21OgEzqznWDDg==,type:str]
                - name: imagePullSecret
                  value: ENC[AES256_GCM,data:K+2xtZAm,iv:5C7XX3jH7acu1hShegF7tryCCnuBEU1lpBb4SdTxsiw=,tag:Uxh9DuObo9x2NZhZRGuo3A==,type:str]
                - name: localDevelopment
                  value: ENC[AES256_GCM,data:AmrPgVY=,iv:QSNVvkk7+KgUFxElm9W6PCc8nXXjW+Tj2/IKRKQ/5ic=,tag:2YYEK1YWf8/zneY1n+E9rA==,type:str]
                - name: kafka.bootstrap.servers
                  value: ENC[AES256_GCM,data:FDt8HS41fdVP9/vE6LFZ5UAGNZIm9wa0XkVa8BJJ/ssV1ZccQukceaJzXIs=,iv:j5Cfc96C64BiK2i1RQzQUC8vBZimK60S2tI3AGU9dbM=,tag:7HDyQ8pH+tmBgD5C79wIww==,type:str]
                - name: kafka.sasl.username
                  value: ENC[AES256_GCM,data:Im9h6s6BxjQnvjj8NcETbA==,iv:QAp9Wit5aY7cC324vNy6BtPTZsb+plVQNj5V23tOyZ4=,tag:hFruUUooi742I78Jz0xnrA==,type:str]
                - name: kafka.sasl.password
                  value: ENC[AES256_GCM,data:3u0SwRxW285NZUNL3SieEK27+d7KrB1Txa0uGM0hFbvavDEEtQa7lfW4J2fu2JzQHriRazWFiluXfZ9uyelMwg==,iv:73Irhwhckz9TdBkM+jX+cVOURvXXLuJAY2aFf4CHNLI=,tag:Xj6W6/4IM9YAt9XMN4c9AQ==,type:str]
                - name: dockerRegistrySecretEnabled
                  value: ENC[AES256_GCM,data:20cRZEo=,iv:Kgh4buHXJ73SUlxpKS/P04MarvPtXeStzh0QBlcQjV0=,tag:El3h9jo1NgxOEUlPK6eJyg==,type:str]
            valueFiles:
                - ./values.yaml
    destination:
        name: control-plane
        namespace: query-history-db-loader
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:662260526581:key/3f226811-712c-49d1-a5b7-de59223ec1cb
          created_at: "2022-07-14T21:12:40Z"
          enc: AQICAHg1QZDATeVp971NNJF8tQQgf93gP0h0ctR/hGudQ4wAMQGqorPL33tow84AynbhDXnPAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMq5S61G7an1F5MBsCAgEQgDtdxqowpaWSa2BQp9uLZyMAxiyZpoklSlQ0zCNxQ+LLQ8+4Ye3tV6KvPdezAKKE9KPoK0SATA0ZjXiG9A==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-14T21:12:40Z"
    mac: ENC[AES256_GCM,data:Z/R08amGFkbmHqGFHLMOt8xmOBvKqH0PPriSjc4Pvx3DrHQU2cCCMHy6h8c+ZU/LlKjeeBp7IaL5TxtLORCj4GKytOfCgWcZrPRHurYqemOeZb+z/Q+0QafqwYXce2tLt1+U+rOf6njhAtAO0R1A+AesFK9LFVoLBMmdDvuOUqM=,iv:On0/Tv86LKT3JiZkkJHqOQJB33NfryrRpLctMjMQBAE=,tag:4J99VAgvAqmg2uKHib9QHg==,type:str]
    pgp: []
    encrypted_regex: ^(value)$
    version: 3.7.1
