apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ego-portal
  namespace: deploy
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: galaxy-dev-notify
    notifications.argoproj.io/subscribe.on-sync-failed.slack: galaxy-dev-notify
    notifications.argoproj.io/subscribe.on-sync-running.slack: galaxy-dev-notify
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ego-deploy
  source:
    repoURL: https://github.com/starburstdata/stargate.git
    targetRevision: 8d3b6724b1395c8f8960b92df5ba5e1354a877b2
    path: charts/portal
    helm:
      parameters:
        - name: image.tag
          value: stargate-3620-g8d3b6724b
        - name: deployment.region
          value: us-east-1
      valueFiles:
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-portal/dev/_base/values.yml?uniq=f486acfd-f87f-4b0f-9e9a-8c00c7ea7819
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-portal/dev/_base/secrets/admin.yml?uniq=9186EAD0-C35C-4801-B7AE-A0FF15BCD93E
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-portal/dev/_base/secrets/billing.yml?uniq=9186EAD0-C35C-4801-B7AE-A0FF15BCD93E
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-portal/dev/_base/secrets/db.yml?uniq=9186EAD0-C35C-4801-B7AE-A0FF15BCD93E
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-portal/dev/_base/secrets/demo-dataset.yml?uniq=9186EAD0-C35C-4801-B7AE-A0FF15BCD93E
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-portal/dev/_base/secrets/dispatch.yml?uniq=9186EAD0-C35C-4801-B7AE-A0FF15BCD93E
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-portal/dev/_base/secrets/github.yml?uniq=9186EAD0-C35C-4801-B7AE-A0FF15BCD93E
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-portal/dev/_base/secrets/intercom.yml?uniq=9186EAD0-C35C-4801-B7AE-A0FF15BCD93E
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-portal/dev/_base/secrets/kms.yml?uniq=9186EAD0-C35C-4801-B7AE-A0FF15BCD93E
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-portal/dev/_base/secrets/login.yml?uniq=9186EAD0-C35C-4801-B7AE-A0FF15BCD93E
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-portal/dev/_base/secrets/mailgun.yml?uniq=9186EAD0-C35C-4801-B7AE-A0FF15BCD93E
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-portal/dev/_base/secrets/marketing.yml?uniq=9186EAD0-C35C-4801-B7AE-A0FF15BCD93E
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-portal/dev/_base/secrets/metronome.yml?uniq=9186EAD0-C35C-4801-B7AE-A0FF15BCD93E
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-portal/dev/_base/secrets/segment.yml?uniq=9186EAD0-C35C-4801-B7AE-A0FF15BCD93E
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-portal/dev/_base/secrets/query-history.yml?uniq=9186EAD0-C35C-4801-B7AE-A0FF15BCD93E
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-portal/dev/_base/secrets/security.yml?uniq=9186EAD0-C35C-4801-B7AE-A0FF15BCD93E
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-portal/dev/_base/secrets/signup.yml?uniq=9186EAD0-C35C-4801-B7AE-A0FF15BCD93E
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-portal/dev/_base/secrets/stripe.yml?uniq=9186EAD0-C35C-4801-B7AE-A0FF15BCD93E
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-portal/dev/_base/secrets/tls.yml?uniq=7D65148C-D279-4A0F-A6EE-DACB556B9312
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-portal/dev/_base/secrets/userflow.yml?uniq=9186EAD0-C35C-4801-B7AE-A0FF15BCD93E
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-portal/dev/us-east-1/_base/values.yml?uniq=075f1335-e4b8-4f19-b56f-5fa98767e0eb
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-portal/dev/us-east-1/_base/config-properties.yml?uniq=1F128AA3-BEB7-4F3F-9BB6-8158F487A5A0
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-portal/dev/us-east-1/_base/log-properties.yml?uniq=51B9CF53-EC28-4311-8070-8C4F24ED655B
  destination:
    name: control-plane
    namespace: ego-portal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
