apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: billing-aggregator
    namespace: deploy
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    project: ego-deploy
    source:
        repoURL: https://github.com/starburstdata/stargate.git
        targetRevision: TEST_SHA
        path: charts/billing-aggregator
        helm:
            parameters:
                # this is used in the nats setup job
                - name: metronome.authorizationToken
                  value: ENC[AES256_GCM,data:f+09WBgYdKnZ0QLwSaoMuskRtUb3VPjJlhZ9mu5jQKtyfLkB7Vhhy5riDafxAcOuvPLMeoxgosTRLrl3DldGkw==,iv:H6Gr18AMeYx3G0vD0RvEO5E7f72ISqFp5GY/TxgryDE=,tag:Sraq2x5kUcEeLb9k1pbqBw==,type:str]
                - name: imageTag
                  value: ENC[AES256_GCM,data:iVloiT8886s=,iv:Y7PPa/GTYdwwLLb/aW9yWJntkmHNWo2PfW4CUMs2sHo=,tag:dPpZmeTdcVlEqa/2lr/kjg==,type:str]
                - name: imagePullSecret
                  value: ENC[AES256_GCM,data:skcFD/Jz,iv:Hl9FMy9aDY2XzNQuR0t3nKzMKayq2kYEaLWdzlk/j6Q=,tag:2KHIDI8+E4jzf/zPpTbrLg==,type:str]
                - name: node.environment
                  value: ENC[AES256_GCM,data:1UiX,iv:+h10ceCBekkukPnvNWRl5Retd7VgCvMpnMPynvA/Xzw=,tag:sIor6f3r2LgfcDPZiCQEkw==,type:str]
                - name: localDevelopment
                  value: ENC[AES256_GCM,data:69byEAg=,iv:scsoszwRzihm9YD/gdDPBrDiYghWEB81AkdR9v5t7qc=,tag:zcBrfBX5NkpemmbATRWo0A==,type:str]
                - name: prometheus.serviceMonitorEnabled
                  value: ENC[AES256_GCM,data:6M7ktg==,iv:pX8yIvYmTznQlM8cjmqoULQKE10RZugFXdFam7WLbR0=,tag:UQoOfkzGDlHG1kYGEfaSWg==,type:str]
                - name: dockerRegistrySecretEnabled
                  value: ENC[AES256_GCM,data:p4OreJY=,iv:+ZZzeu1euz45pdUrbrt6KD463kWr1UyUTcQmAJmvAn4=,tag:eHHyH8SgINH96iV120ydhw==,type:str]
                - name: kafka.bootstrap.servers
                  value: ENC[AES256_GCM,data:f0ef0Y3+ScE86yqDQ2COICSsTFLi1xm/1dmGamzoJuowBcFouMwUgBvY+F4=,iv:TUfaOA8FOqUCKRGQTxzP7sL8/neqK1xQfP5gomlO5iQ=,tag:dHDJb8547Lr7KvFXETPKOg==,type:str]
                - name: kafka.sasl.username
                  value: ENC[AES256_GCM,data:UGz7rsZhbOAkpwUppuINHA==,iv:BgwQ6gp2IpGXsL4Aln6oYw3mBubdVmoTZagORGpYdsI=,tag:fqDNZ2uBphTLE5/0QSW/QQ==,type:str]
                - name: kafka.sasl.password
                  value: ENC[AES256_GCM,data:wGuoR+T7jV1KyEI4Yc/dKa6wI+jS4wNP5/I6DRI1AXT/cBDkAVq7YFEWlL9MtpqUi4V04Ag6VPRBP5Bh7AtVGw==,iv:mgdO+TFB7G36QxiMZaRH/wrqqGBmTN8KeXIVsFol0Qk=,tag:sWg0ccyCBOReT5H1aZE8Vw==,type:str]
            valueFiles:
                - ./values.yaml
    destination:
        name: control-plane
        namespace: billing-aggregator
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:662260526581:key/3f226811-712c-49d1-a5b7-de59223ec1cb
          created_at: "2022-07-15T14:34:46Z"
          enc: AQICAHg1QZDATeVp971NNJF8tQQgf93gP0h0ctR/hGudQ4wAMQH/JPA6S4hEPJkhMyhcK21nAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMbT1VyWN0dcnBSE6eAgEQgDt9/2AkTP52pRBWFxH9+XaXEZKgTYFjL83e6NNyFM9G3Kh8til2w5aOGCshAHSSyIpNmZAZYa+H5cECVQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-15T14:34:46Z"
    mac: ENC[AES256_GCM,data:c+uwJp5mTtzTKenBzXwjaBwBO23aIc8diHbCbfbqcRJQvCdKv0i27SCdlWnqZodylr4Idh83UCT4GZPYYA/QAYgnAzFQXrowOuQYgyBfODx+2PAXHrkQHQEYZRSkiZKViQo/lbcjWT8+UkajxUVT7kfY9WeK4LLfj8DkbW6iUEE=,iv:8L1b40BPDUZ8S7ecAZS91M2lDyDA6TtbE+ZqnOrJ9So=,tag:+mXOMe427IpiGO0e0FSdPA==,type:str]
    pgp: []
    encrypted_regex: ^(value)$
    version: 3.7.1
