apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: billing-aggregator
    namespace: deploy
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    project: ego-deploy
    source:
        repoURL: https://github.com/starburstdata/stargate.git
        targetRevision: TEST_SHA
        path: charts/billing-aggregator
        helm:
            parameters:
                # this is used in the nats setup job
                - name: metronome.authorizationToken
                  value: ENC[AES256_GCM,data:KdgcxV4bVTogedoQlF0VdXOvra/j+TQOfndrV7+G4H1UCWwXwQfFX7V8yCA+K0QmMMtdPnSSYHwYndM8ZQv2mQ==,iv:UEZMaDgcAbPDW+QH8R+StLaMxVZxnrbyYu3hPVwFBuo=,tag:2CvaREZ6izMEKHj803Fg3w==,type:str]
                - name: imageTag
                  value: ENC[AES256_GCM,data:8SY6qVy57tg=,iv:uHPEt+Lb0yZKAz53pkYhg7xjmkrkLNaCdlkdxXxEVco=,tag:3wuAg/kwKXSV4zFFdulB4Q==,type:str]
                - name: imagePullSecret
                  value: ENC[AES256_GCM,data:SyK8Es1s,iv:mAeYOHYK5q6KByKZMMoloUGg5+k3n8WdprFTOVDde9o=,tag:dgcpMVm1ir0z2/NhpyAaaw==,type:str]
                - name: node.environment
                  value: ENC[AES256_GCM,data:ZyoY,iv:ohLo8C5JawLhQJxwN694VRCDcanHZTPYuIO5Xhtrx8Y=,tag:Bj0XbWbM0hzNaYdezM65lA==,type:str]
                - name: localDevelopment
                  value: ENC[AES256_GCM,data:CRjrXeQ=,iv:Jx0bpKilZAUxgB0d3IPbLWSEnz/Mne0vqdtFzfO4mV8=,tag:2PCkFTj/9GE2gHy7ixtggA==,type:str]
                - name: prometheus.serviceMonitorEnabled
                  value: ENC[AES256_GCM,data:O6cgZQ==,iv:nyzcw3swhJRBGNNLKjDKNyjggKLDVrlvRm3oo5BfVzQ=,tag:n1tpu9+i9yVvGEWKxXjdTw==,type:str]
                - name: dockerRegistrySecretEnabled
                  value: ENC[AES256_GCM,data:vvwC0eI=,iv:H9WKYpd6QbC+kg7OOc/ejDQvGMlCHg2N4MXB4Dd1fso=,tag:GTFLG2OuV+tNLwGPOiZp3w==,type:str]
                - name: kafka.bootstrap.servers
                  value: ENC[AES256_GCM,data:94TyZXHDojN1uIj1DcWyWchRzAv3WARc6EgItObc1qTwIUF8RtXCoqBvT0k=,iv:gUr3qOwUzHrpwMo5XBb3EkQ/Kp6CdqyL7JUxrE7w63g=,tag:LEw43YsnWolG50I9tcGWew==,type:str]
                - name: kafka.sasl.username
                  value: ENC[AES256_GCM,data:GQDXQtjQoBNlzKDBqWafUQ==,iv:LeSpMP2M32jfS4xSZYXO5W+zkYPmISPnWdWRju35mC8=,tag:EF6+7o4IHV16xPHyNsirZg==,type:str]
                - name: kafka.sasl.password
                  value: ENC[AES256_GCM,data:zC38UWng1EjjpPgeKkqiAD/3KqjqlV/fgfCaUaLKccMLu2IjFo7UlOVO3UzrJmjEjNtFRD6FAtOJuq6MKgkCmA==,iv:ZJ+aFT3b/xtQGSMzQca5UuioZw3YIuLg3wID9W9b1KE=,tag:9Yngl+3e6u5qNCrTfsRwow==,type:str]
            valueFiles:
                - ./values.yaml
    destination:
        name: control-plane
        namespace: billing-aggregator
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:662260526581:key/3f226811-712c-49d1-a5b7-de59223ec1cb
          created_at: "2022-07-14T21:12:39Z"
          enc: AQICAHg1QZDATeVp971NNJF8tQQgf93gP0h0ctR/hGudQ4wAMQEwJX5B4xF/hl7AIiyi1oRZAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBTJFA85L8ZzDR6UVAgEQgDvV7RIAzCfsyRZ3L/eI+tLmzc1Ts1qNdJtDIrgtcaJ6/nJqL+D1GSe9fA32pG8Jb7QIBdmP2YzvIHIt8Q==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-14T21:12:39Z"
    mac: ENC[AES256_GCM,data:iymMa2RoBDfHEluVFBjYsoggT7Wpb6zDyKL7/7L2bQ3Oknzvm/cfs1kWkSGmcVqFRU7NJr50WRX0HZydBDwNmP89+2i1IW8Yl97gTQeVB2PjoGxIzSolK/4lZJWtoGv4DKiWxfo9gufZ0gjHhWb4GIw300hYQA2KAHTUWeu4oj8=,iv:UPEXD5LA14so3Rxk2Qw/CqKCgD9qDMVANTPqSXWB69Y=,tag:KcUFET1YXLKUy2Bn3TQuAw==,type:str]
    pgp: []
    encrypted_regex: ^(value)$
    version: 3.7.1
