apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: billing-aggregator
    namespace: deploy
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    project: ego-deploy
    source:
        repoURL: https://github.com/starburstdata/stargate.git
        targetRevision: 8d3b6724b1395c8f8960b92df5ba5e1354a877b2
        path: charts/billing-aggregator
        helm:
            parameters:
                # this is used in the nats setup job
                - name: metronome.authorizationToken
                  value: ENC[AES256_GCM,data:S62jrTA/IqPDhN8IaPwCMw5qNdCvsCmSTTRTt9jfxiG89OnELLmDaftobhHHX/DwGwT1t+Eq0vRYbe/Sj9qj6Q==,iv:WsEmn8ApNFbDkLZondtC8TRC7Y/rtLPOuyEGDqVHPJI=,tag:vCjaqB3NAYbgepLspZdmQw==,type:str]
                - name: imageTag
                  value: ENC[AES256_GCM,data:TU0GFAai0UqeO0vyCdni3a589ogh4UTc,iv:nHAs9KfnRLPjuEn46ptSx22kWMLLw3i6jeaDUFx9oqw=,tag:K02M0zNYPlfijhMtWdw/Nw==,type:str]
                - name: imagePullSecret
                  value: ENC[AES256_GCM,data:6uazU+ED,iv:Q+3JAuFDK23W2uYBCgO2XjjlgM2uexd6zy8KUW3qx98=,tag:lXukfAa4fFp1CmXMPwRDkw==,type:str]
                - name: node.environment
                  value: ENC[AES256_GCM,data:BX7e,iv:rOKIrXI7tSXghLi8NmfeP25xOyiqCBOTLQNPjnpW+wM=,tag:p5YZBn1p55gGYEjt7Oentw==,type:str]
                - name: localDevelopment
                  value: ENC[AES256_GCM,data:/rRiNsg=,iv:2fzwBkOCejFpn/qgp/JodKd9aBFVl/vFZ42qIMetdBs=,tag:zuA2MjDpaWkZ/2LCjdgVaQ==,type:str]
                - name: prometheus.serviceMonitorEnabled
                  value: ENC[AES256_GCM,data:0HNnZA==,iv:Q5PYL3yNCjw2ZwtCat/mIwMCwL+Ci3W6fEicb0poX+s=,tag:5tFtTBF68v8xFnJbRa4i9Q==,type:str]
                - name: dockerRegistrySecretEnabled
                  value: ENC[AES256_GCM,data:nsA6V/0=,iv:555VuNtVw9olXsQHqAiooTxhLzDqc1hjmgX0ikW/B9Q=,tag:qfc0+ugEpEgx4/dWsGwwtQ==,type:str]
                - name: kafka.bootstrap.servers
                  value: ENC[AES256_GCM,data:hRMM8OCm1BmEWvGEyNnEk1J1KLLN68BEGnK3dNm6MJ7lb1x6kbIGG6+WeGU=,iv:TSmyDS7hgVEpCc6CVHV80TdNWdoDiSVNFBPrYKSgCNQ=,tag:eLYuONUroZ3kt8jGnPGIHw==,type:str]
                - name: kafka.sasl.username
                  value: ENC[AES256_GCM,data:O/ZyEMUzI+KbCnsUVso3vQ==,iv:GLYvvcN8eXQHlyJKsT6a0hM1yiWyPZOKF0etxF82/ZQ=,tag:3u/rzIX8k3okoz7F3wUqAQ==,type:str]
                - name: kafka.sasl.password
                  value: ENC[AES256_GCM,data:v7byywfREXwrncpgxhF/4bvDFjRyOp3XwYXpD7bRlWWO1NppGA9ACR43Cyif2IeBWnhfSryNVieyoAarIA0tlQ==,iv:/lYs4P4WQGUZLWjFr/2a5GkI9lgV3GmED88XiTMnDwo=,tag:8yU01ByL5icDo5xNxR9Itg==,type:str]
            valueFiles:
                - ./values.yaml
    destination:
        name: control-plane
        namespace: billing-aggregator
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:662260526581:key/3f226811-712c-49d1-a5b7-de59223ec1cb
          created_at: "2022-07-11T18:16:23Z"
          enc: AQICAHg1QZDATeVp971NNJF8tQQgf93gP0h0ctR/hGudQ4wAMQGxIFOqppw7d8UC9dDJBicxAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMrhv0cSB4pPsjM2FXAgEQgDsxCdm/2TV+kN6y6gPYOmlqCHQB4IyO4PXnyA+Lmh4tjaUairEPT4fjiwC9S49GkC6GuUfxd5KnNWGITg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-11T18:16:24Z"
    mac: ENC[AES256_GCM,data:SixPNUoarRSx9jjg5+tRAKcdSGBBt8sUAFLrx4/nXqKs+sn9+fnWoJuOybI/Kc8NUF/FDhKLVTFcKGDWzFkaVs4B+7WIQEE0RTqNyLg2VCWNaUeemILeE+xuimfV5yP2+IBd9rvkfqSs3BmckAjv6m0PoYoRLePQrFpimyCiP/Y=,iv:zVzXo8EyGoLnUdQIp+Uu6DtUSr8Jt2dP5+ZK/D4DeM8=,tag:COZ15fQ5IcWjtvYRF6TC2g==,type:str]
    pgp: []
    encrypted_regex: ^(value)$
    version: 3.7.1
