apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: billing-aggregator
    namespace: deploy
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    project: ego-deploy
    source:
        repoURL: https://github.com/starburstdata/stargate.git
        targetRevision: TEST_SHA
        path: charts/billing-aggregator
        helm:
            parameters:
                # this is used in the nats setup job
                - name: metronome.authorizationToken
                  value: ENC[AES256_GCM,data:EycoLjEXiMVSehPBfxtyHOzIqgC2+08dDxsRucH4LKtc3dq5U9+qnMxEJpU/r9Us8KNu+Z8NkjTImisJWopcuQ==,iv:1mqZKEkojt54a93bhPKTTubaUuPyHDFYxuZF8X8EL6Q=,tag:MEnq0TtinNrHb0K7GcTQ9g==,type:str]
                - name: imageTag
                  value: ENC[AES256_GCM,data:Rei7V6wRwzU=,iv:/vmla0lTJTNoKetjxB8Y1LTyV8psMQmyPgxQ2VizuA0=,tag:QKSULQyi74vBU8AYPnOE5g==,type:str]
                - name: imagePullSecret
                  value: ENC[AES256_GCM,data:gdEleea9,iv:FYfLG9spCKQItBJ8QKcFZvQ9H4G7+XIMbwGq6kWnoEQ=,tag:8GMcD4lLZrlGiEauF3tWXA==,type:str]
                - name: node.environment
                  value: ENC[AES256_GCM,data:C9rJ,iv:/cmYpQGMoJ551nXds23OZhSZSaNPSYy2Qmw4LPKZP6s=,tag:6I+RCtA3mYWfmq34zVUhWQ==,type:str]
                - name: localDevelopment
                  value: ENC[AES256_GCM,data:2NOy8EM=,iv:U6B08dGKTxuqGBtO8me5wzXsScVhq6h3pCfeKJ9O1eA=,tag:QYE5277od355DoC3DDqQnQ==,type:str]
                - name: prometheus.serviceMonitorEnabled
                  value: ENC[AES256_GCM,data:edrS0w==,iv:U9QKL7VLnewq0q8h4KmRXNrEVjmSk3KaT1RA1DpC2rI=,tag:YqYUL2UAKiLLkhzhdkO0jQ==,type:str]
                - name: dockerRegistrySecretEnabled
                  value: ENC[AES256_GCM,data:2wR8a98=,iv:s3EVVbfLudKUTI6PNKmH+EInO7ZEcaOz2TfXF+N1kKg=,tag:xr8C9/aZpn3np95QZk/Gmw==,type:str]
                - name: kafka.bootstrap.servers
                  value: ENC[AES256_GCM,data:L3hkEp7eFka2Co+Hw8yO9GV4V+AnFTKp+LuI5pmvZoi3MZWgNowkn4bJqpk=,iv:VBPJfNsthcDyYmDpOCx/bIvU2SsJwVrOcKBvZAXZiHI=,tag:19YzqN9i8UWGq0pPdpp5hw==,type:str]
                - name: kafka.sasl.username
                  value: ENC[AES256_GCM,data:/f2TiMUAb5YiuRfcgtbmgg==,iv:EQ40yBQu/AofhQ4VO8cSxrHTckE4bwujE28NlUXUDHY=,tag:BL8fZwc70NLzYKX/qgb6xg==,type:str]
                - name: kafka.sasl.password
                  value: ENC[AES256_GCM,data:0L8IZ4TsQ0wx3TmgLXcBo9qnqwypsFy9mfhSbCEEag9BMi3xm4i4oeQe2IUcjzzr9DRsM866XtkyJft66fEP4g==,iv:1n7xyvvg3hJMFfTUEjKNVFBClzxWuKJBsVfxx0jDHVg=,tag:pl6WPzgqonVM3aE4tYRnfQ==,type:str]
            valueFiles:
                - ./values.yaml
    destination:
        name: control-plane
        namespace: billing-aggregator
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:662260526581:key/3f226811-712c-49d1-a5b7-de59223ec1cb
          created_at: "2022-07-15T15:12:10Z"
          enc: AQICAHg1QZDATeVp971NNJF8tQQgf93gP0h0ctR/hGudQ4wAMQFCx98OANDzS8Sf+UiendcAAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMdtRpSldFzf+A92B8AgEQgDtz4M4F7Zjc5rDMMrmL9xYv9OAI60xXq82PV6amumOS4dXBCl2Z+uP4pok2Ekh81O6HVtWsD2LQGP5XcQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-15T15:12:10Z"
    mac: ENC[AES256_GCM,data:xS2MQCD3yyTg6nBmMFWrP7+c12mwliVnW1MQPUktOMNI7PYSpZwrj8JAfFUbDxGW0ss/DMVEzM9WNEXT3mAXhq8MN39xgQcpjI2BMXcSbPIVRM8RubfFcC3ueGwraFk5zs+B3WpXHUlCDx58VNtgErND9rARIa6Z46Slinbi7bc=,iv:hcvVuyXyeAn5xf8OicFpI1exakusMrn9bU0HOPI64Yw=,tag:B5WFSdr4s8JrXGT7cOtZng==,type:str]
    pgp: []
    encrypted_regex: ^(value)$
    version: 3.7.1
