apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: billing-aggregator
    namespace: deploy
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    project: ego-deploy
    source:
        repoURL: https://github.com/starburstdata/stargate.git
        targetRevision: TEST_SHA
        path: charts/billing-aggregator
        helm:
            parameters:
                # this is used in the nats setup job
                - name: metronome.authorizationToken
                  value: ENC[AES256_GCM,data:w5sIGg5YLwz7A2HwfVd+DClJ0sHCsubXekM8zH4bROjKMGfFDPO1Z+t9D8rnoZ2cjlGOwaNhJG0bgG42Ra/poQ==,iv:lTuEwaGqN5dK83hVTac/4VVsW5LdtHBgs0hfFjPP2yg=,tag:Ycv7AK69XagdBuH+V+WWGQ==,type:str]
                - name: imageTag
                  value: ENC[AES256_GCM,data:bdFD9mo/pdg=,iv:P6VkuwMAP85jHVXlp/4ZJbPfJIDV91QYBI5yL2wKnBk=,tag:lr3H52DoqXCc8zcmz3D5rQ==,type:str]
                - name: imagePullSecret
                  value: ENC[AES256_GCM,data:rHFP3UUf,iv:sEqz+LJRQedc0OlJSe04HLroREZQ13StLQBzW4jWANg=,tag:9J8p4sA5AK5P3TLpebRgSQ==,type:str]
                - name: node.environment
                  value: ENC[AES256_GCM,data:3mCG,iv:T7/sOIUK4WMw5UATAm9I/37Clc/uVtz1GzlNcJ0e+hk=,tag:qRXYMLfd0tfKdgFW1nAdcg==,type:str]
                - name: localDevelopment
                  value: ENC[AES256_GCM,data:cz5bXfk=,iv:nkxnSxrZPKS+O/JRY+mUeWpVDefyHGTqask1L9dRy2E=,tag:sHMVgeZl8MbTi4g9RNr8Ow==,type:str]
                - name: prometheus.serviceMonitorEnabled
                  value: ENC[AES256_GCM,data:Fi4Mug==,iv:2pY/3P7HZYiJZt6lPSmuf/Pj+VMpwDFMwCPs5sS5No4=,tag:CNDaTF4gHYvfVBy86OX5wg==,type:str]
                - name: dockerRegistrySecretEnabled
                  value: ENC[AES256_GCM,data:PhteQuI=,iv:zf8FjU6M+fR9NM4Q5eyIuY6mbJGrE4DAoUQH8Mkq2uU=,tag:u2N9yLCZcPoqtLrwfIvH6w==,type:str]
                - name: kafka.bootstrap.servers
                  value: ENC[AES256_GCM,data:al+9Pyxo3Bw54e//c+C8DkBye8aZAZLM7DXk//h3qWe7SrzHoMN6/TAFM6U=,iv:GtqQDOk4VYjSNScPDODA1vHhrsHM3YD/dRkfuv4D3IM=,tag:1zcJgqjz0L+8wO1u8gREmQ==,type:str]
                - name: kafka.sasl.username
                  value: ENC[AES256_GCM,data:Sx26XeDRt5A0SMejEFF//A==,iv:DdmgKbPIL8kPYoT9d9FsOnKPJUmeTrSqhnhrMX6mVMs=,tag:V1ti6pDSYH6FAahikPPj8g==,type:str]
                - name: kafka.sasl.password
                  value: ENC[AES256_GCM,data:9JNOcIXB8IFq+9SGvP0HzCTjN0p/dDlBHavyCVRCG6k/iuCWE8dYpMbOccpR1vGkq0snXo6b4PSgIoLvvv+cbw==,iv:Mr4emjXtJHEkRufomoNiemN3Qs98+cem3aEiov9NfZ4=,tag:u8vupQkE2GfOrFVqjORGUg==,type:str]
            valueFiles:
                - ./values.yaml
    destination:
        name: control-plane
        namespace: billing-aggregator
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:662260526581:key/3f226811-712c-49d1-a5b7-de59223ec1cb
          created_at: "2022-07-15T15:03:18Z"
          enc: AQICAHg1QZDATeVp971NNJF8tQQgf93gP0h0ctR/hGudQ4wAMQGykroPKQrYo/zEBSns6r+jAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMlKfyMRYoytLB/TwxAgEQgDu2tBSVnPjJjL8sR48jlUQT5Tq9lkZlR8QJgraiIUwatgKsCY22nhgPOM5xpGS+VAs0/yIXBMeOF0Py6g==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-15T15:03:18Z"
    mac: ENC[AES256_GCM,data:3yCLq36HJh5fEdlxNNFe8jknvF7ztu5iZTRXQ/0NrPHG/+qD2FCEzvuAuRiNlEbmvNQrn4ZHciIQ47P+CVv+74m7btUO/zkjI+KMHA0mwXSsuMqCLOCCAzrc90YCuaXQbwNlvEkcJH+WHq1mbfTBc5JJTA9AvHLRXn1yBcUkvGw=,iv:bRsge3VYN+TtgHvNRw9La97J2RAU6JAH5yimUgCAwPk=,tag:yJ7qcNJw0Zenb0AoegyGzA==,type:str]
    pgp: []
    encrypted_regex: ^(value)$
    version: 3.7.1
