apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: billing-aggregator
    namespace: deploy
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    project: ego-deploy
    source:
        repoURL: https://github.com/starburstdata/stargate.git
        targetRevision: TEST_SHA
        path: charts/billing-aggregator
        helm:
            parameters:
                # this is used in the nats setup job
                - name: metronome.authorizationToken
                  value: ENC[AES256_GCM,data:RJLTrEkIDkw3iCiaInUZ7RE9DcjWOpMz3tD+cnmtHeA/LeDnG/udT6utKZdjJnQgxJWApNjr4tN6YmXrWZ6T/A==,iv:iCyYMoMohDg2lSAHphvymeLjkPyaM9iWIpMMTlNSBbQ=,tag:DVQTG/b0AD39r6asZ0KqIQ==,type:str]
                - name: imageTag
                  value: ENC[AES256_GCM,data:tok2wfEu3Fw=,iv:PMNnK7zoDTeQFHBeUiK8bMndnqyZDWKM3iakPYc1mN8=,tag:BWcsRIgklQCXq/g/k6/ODQ==,type:str]
                - name: imagePullSecret
                  value: ENC[AES256_GCM,data:USpJngZK,iv:cuxX2FKQmBz8v5kwO5vbvZWsOcJ6KPMT1qyCf77V/bA=,tag:3DzlKzdtEqElxJCHMhh7hA==,type:str]
                - name: node.environment
                  value: ENC[AES256_GCM,data:Wl1m,iv:gKrsuCeL9cJ2fY4sAewYJLaBV1MEusWxPbvh2YwrqvI=,tag:qMPMZuzkVAgExy7pE5KwJg==,type:str]
                - name: localDevelopment
                  value: ENC[AES256_GCM,data:PL1jzrQ=,iv:kYQnemSXr3ZSHmtJRp3oMwASZ7V3wqxqpQVmA3xfDxo=,tag:Oz5R8/+hzPrwAvFSYpqbKA==,type:str]
                - name: prometheus.serviceMonitorEnabled
                  value: ENC[AES256_GCM,data:0X9Mog==,iv:VouMz1iFRovjR2bbID/wKGIIC7HDozKRDzpVLkwhLmU=,tag:CMD1iOjqZbZS06Zl0kQi2w==,type:str]
                - name: dockerRegistrySecretEnabled
                  value: ENC[AES256_GCM,data:HFdpS1Q=,iv:H/EuzsxTH84mjy3Q8Yw0yiW4Kh8CfRttcs1q1kJEt2Q=,tag:rsrUYeYnEHnZmvAAs1pH1Q==,type:str]
                - name: kafka.bootstrap.servers
                  value: ENC[AES256_GCM,data:i2N+4nsNMn+L+fmQDKdv3MQvD691xtV9M+Cc+eqyr8AUo17ZSm35h5+KRF0=,iv:YqdDIb/7kHuEa+XJqlThoIKyDmZgq8m22+kYcHNjByY=,tag:YDYyg8NjZEQImyOn6ZvH0A==,type:str]
                - name: kafka.sasl.username
                  value: ENC[AES256_GCM,data:DTsoxWxYnuOjj3cj76La0Q==,iv:LSyswg7kj7tIy3w3f+HMl4kTdLBjfqHGscxf05CdB9E=,tag:6EqzuvIjw7LEjbl1kZpPig==,type:str]
                - name: kafka.sasl.password
                  value: ENC[AES256_GCM,data:0El6nw+k2l+02T6EKa1QQD3lg8Ijn4LoU8Nqudx03mcO8ktZPUr5dLnFK64Bp6loA6G+e/wacEqOwoO55lriaw==,iv:MgzQHgiN2dLbqIPg3CncAVX8kflrxuNx+nBvph2fnAA=,tag:WlHevwitx6DVuJNpMWth5A==,type:str]
            valueFiles:
                - ./values.yaml
    destination:
        name: control-plane
        namespace: billing-aggregator
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:662260526581:key/3f226811-712c-49d1-a5b7-de59223ec1cb
          created_at: "2022-07-15T14:26:56Z"
          enc: AQICAHg1QZDATeVp971NNJF8tQQgf93gP0h0ctR/hGudQ4wAMQG2xt74+cR9W231REln1dx3AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMRnKiSB5BjdpeEt8JAgEQgDtbCQtzfqn/cTauexxZRqyx70BTMvIYR4AZ6hrAG8Ij7MpS8Rbb6v9PLW/UrMgk0GRvXSwpWz/Ud5pLug==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-15T14:26:57Z"
    mac: ENC[AES256_GCM,data:zj3SeObfN2MWuh9H4z905pmkDMOoDeRYoh00E+pb3Eza71IhM6RBmbcK7yYRr9M6hyfjyEhBMaaiexr5iEtsNQCTkxH9tZl+eGNH9JbzkTNBXtIZ9FrRQqIoo244+g0jr6mcSE7GO7yOrqjYaLa4tWG4FRL+KwxrA9sQnLAvLJ8=,iv:dr80tR53Wd2aYMUfLmT+EiSwo4zumbf3kST1y+gpE7o=,tag:K06M0q/pKs5R7RtVK5XiGQ==,type:str]
    pgp: []
    encrypted_regex: ^(value)$
    version: 3.7.1
