apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: billing-aggregator
    namespace: deploy
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    project: ego-deploy
    source:
        repoURL: https://github.com/starburstdata/stargate.git
        targetRevision: TEST_SHA
        path: charts/billing-aggregator
        helm:
            parameters:
                # this is used in the nats setup job
                - name: metronome.authorizationToken
                  value: ENC[AES256_GCM,data:Av5/xoTvto0bZzaP4QYsLcsj8bi0/It8T21iK6HEPF124Z5RfE0rq6rp610wfg/IWsUfQ+64FWRI7nIlRgVdLQ==,iv:R6GtCJhxBs3ceWHaiQd8bu7jUD9e0AVIgectq3ga+Ig=,tag:JFspC3Sa1hXMAMRCa3J0sw==,type:str]
                - name: imageTag
                  value: ENC[AES256_GCM,data:vB4J4ucSt10=,iv:/vY2XXTJ1WtuBZFRGD0JmP4RnuoAEqs6ECJwnyuFAR0=,tag:2LYbaNBCjNXZ2n6mb4fgyg==,type:str]
                - name: imagePullSecret
                  value: ENC[AES256_GCM,data:N++tgST6,iv:UqUL8qeYhmBw4tZt9TF21MsmkF7eG4+1nujQePADBB4=,tag:1Jyui8XEkcP224zY4Az08Q==,type:str]
                - name: node.environment
                  value: ENC[AES256_GCM,data:5B3g,iv:M74DzsIYDu7fuZ3clF9fbzIti2+w/x/5JJQA2RlECXQ=,tag:hendSBzib/uAVlWu2Gw66Q==,type:str]
                - name: localDevelopment
                  value: ENC[AES256_GCM,data:iFyefDg=,iv:YVc0RgpkSHV7pHXkZ/y6RSUKjEQIuNUimMOQdr6WTiU=,tag:rZJD9BgvJa0iz+ezgXnDlw==,type:str]
                - name: prometheus.serviceMonitorEnabled
                  value: ENC[AES256_GCM,data:KQpHAA==,iv:dPfuklpSq3iNQfGLR1M+BLBYG3pk+KZ7QsnI/sDDNW8=,tag:GhHY02p+jLlkcDFXTxD4zw==,type:str]
                - name: dockerRegistrySecretEnabled
                  value: ENC[AES256_GCM,data:GUska2A=,iv:iBRux6dLvQS5+RFCvEnz2Z3wxlfPVcSDOsgU8ajZIi4=,tag:hgJFSQX0Y3oYiyNt2LfeqQ==,type:str]
                - name: kafka.bootstrap.servers
                  value: ENC[AES256_GCM,data:lpI75AS8RQjBpbNUDy18FBqopDIBxBFrE5AkEMUfNpiWn8pA5qdIf9x/qto=,iv:g4pKq20BSAo9kL8/Ye08P365yNYmQyYevNcoyKTph38=,tag:y7rYtGrDju0OiTtvMQagBQ==,type:str]
                - name: kafka.sasl.username
                  value: ENC[AES256_GCM,data:VEr2QHvp+cBtaLQCerneTQ==,iv:BZdiEZ5Uaf5JdVy5Flt4C0GbSOaBabunKqQihANc1KY=,tag:IXwRKVXTM2QqfnFccY1q0w==,type:str]
                - name: kafka.sasl.password
                  value: ENC[AES256_GCM,data:gMhJQSxpZT3uS3qndZMn1N+qVUBMNAePqqgZaCO3D+1CsdZH7CFm15VbZAnNWW1vdKSSjR+8S+GZoVkD6JIaEg==,iv:S+TolfEbPQGFHKQeaU5Nwo3qFlv/vre6BIyMYILPulQ=,tag:FbRlmu0Wp64yRPWTj2gKnw==,type:str]
            valueFiles:
                - ./values.yaml
    destination:
        name: control-plane
        namespace: billing-aggregator
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:662260526581:key/3f226811-712c-49d1-a5b7-de59223ec1cb
          created_at: "2022-07-15T14:55:35Z"
          enc: AQICAHg1QZDATeVp971NNJF8tQQgf93gP0h0ctR/hGudQ4wAMQF30pvoaOcO7REjoLZoggmFAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMT93pkZatj45R58fLAgEQgDuW23lo6O5Q2E486MtnhLxrxBJ6RKDO74n+JAdeTNagMlGXuobeBa3XHi3vDXYrvmNJ1RbAOMW14ast0A==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-15T14:55:36Z"
    mac: ENC[AES256_GCM,data:oecR1VOhRclRpfVNUmHfaqJYIwG10fe/dsDoik/pLkNCI/reJ5g+qgnU0HgIwnavSNXSr10+SUd9Fa2c5L5czdoAG4uOw9OpXPAXjK7T8TDyACNSe7vN/mg25n7omtpiFKA3VbTIjM9lRzxS8XsWp57y+bVSXsQiVf+9gLTLcBI=,iv:3UzzV/ajVf1hE4gqDe/+U1xfirO2JvTvXEnfbmJJ9Iw=,tag:5m5UYa0RRNO0Nm/rfrgDfw==,type:str]
    pgp: []
    encrypted_regex: ^(value)$
    version: 3.7.1
