apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: billing-aggregator
    namespace: deploy
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    project: ego-deploy
    source:
        repoURL: https://github.com/starburstdata/stargate.git
        targetRevision: TEST_SHA
        path: charts/billing-aggregator
        helm:
            parameters:
                # this is used in the nats setup job
                - name: metronome.authorizationToken
                  value: ENC[AES256_GCM,data:eCoNJlQWSyWq4a3c7Ck0lL9CWbalpIPWpTh8dIqGVc3M5/lTk6z8oTjWYwjINWwJM+HP4dNFgijYMxYDU+P7tA==,iv:Dn/zTWIEFxT0FZeptrC2D41M6MvYzLf1TiJQicrS6L4=,tag:K2dA6Cm6mRMO0MCCe705HQ==,type:str]
                - name: imageTag
                  value: ENC[AES256_GCM,data:ENaHbUQmvuY=,iv:poBuDv1KHRgmLhY68SmCSfma74zSzh3O4Jtc9b4mttQ=,tag:Alq8tgTSSeFe8a1zlsiQ0A==,type:str]
                - name: imagePullSecret
                  value: ENC[AES256_GCM,data:e9D080Ro,iv:tyzc+fb/G2RCVxBUVL7JAzJ1jQ2Ndwk9SI2GhSGkOfY=,tag:Yhd1InTaDNST+lFJgR5X/g==,type:str]
                - name: node.environment
                  value: ENC[AES256_GCM,data:C4Um,iv:oBYIaOJby+l66QQLE1LyfqEgWjW7nVJPiVNxWgnFijg=,tag:5w07tWyamTmMGUJTNhWMDA==,type:str]
                - name: localDevelopment
                  value: ENC[AES256_GCM,data:CXm1hOo=,iv:xYK34koMg9jVBFg1zXKvbb+68bOQpiuNGDGhhtHYeM4=,tag:rDs3gsWnG2Ofc3hnYkX4tQ==,type:str]
                - name: prometheus.serviceMonitorEnabled
                  value: ENC[AES256_GCM,data:KRwjTQ==,iv:c4toql+7p44ComeXdePe0ndtr5CrYoWFzFZ6jkzSEqQ=,tag:LEbpB6sdXjIeL/kk0eS+5w==,type:str]
                - name: dockerRegistrySecretEnabled
                  value: ENC[AES256_GCM,data:WdAVCXQ=,iv:O+TWTogkZOcAupKVRQECNTAaYPy7f1qi08nhaYZ/uNY=,tag:9qRfA5oSCc8B7OPgK3CQHw==,type:str]
                - name: kafka.bootstrap.servers
                  value: ENC[AES256_GCM,data:PPpDJlr0ChezUlTFusJbL5+tT89+67H9q/197le8kEyRYKmfVMy4WQwDz1M=,iv:uhMNoIPyki3v8onr7ReuRvbnT5O3mdInQ/UxWJTNiDA=,tag:nyzpghMA9DEwoaS12rYeGA==,type:str]
                - name: kafka.sasl.username
                  value: ENC[AES256_GCM,data:dD1S/F19RgUfJjVjgQEXoQ==,iv:2M44phaonSy7o3uuHvtI/yrgl8TyJ6oCRTboglHXYpE=,tag:foECHwyyBrvQvcdYH827Vg==,type:str]
                - name: kafka.sasl.password
                  value: ENC[AES256_GCM,data:AeTZ2ynp7szmQIC6t601cpJqOpkJT+n6cX78swmxkDm36unYv+UA9YKLs1Vag0UvxO9mSSWUg++d38N+ndZu7A==,iv:g+rjJEO/c6yKcZeSproEfA3eDpqeshNojbhY1iLVAug=,tag:J1PRkNvQgOtpSSasff5DXw==,type:str]
            valueFiles:
                - ./values.yaml
    destination:
        name: control-plane
        namespace: billing-aggregator
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:662260526581:key/3f226811-712c-49d1-a5b7-de59223ec1cb
          created_at: "2022-07-14T21:39:42Z"
          enc: AQICAHg1QZDATeVp971NNJF8tQQgf93gP0h0ctR/hGudQ4wAMQFWEsdHonfBZCGv2yb0j93RAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDHspgC0KkNzyWIrJAgEQgDtTGHRzToXkX79x8ZmmIOFRQx+u059ZAuc46BTwgap8FIK/ouIhyJui8LADDKJb9mQEn+3Jo2TAxxOE/A==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-14T21:39:42Z"
    mac: ENC[AES256_GCM,data:fVq1nfI3PtDJhQRMQONJks5ZxDL+1XbSTZrVmrObdFr3e+hEzn/RoovK5znCPPDeYWoG1F3nVmjJlQA4Jyb2xSzXc0V8DR8cQ9vrwD1OoBb8K94hBvfS1o9DB1aq9hADnTKRrnXwsGq4PQhlmbGE3hm3NBEDR1l3K111xrVH3jc=,iv:l19JZj2+oDPRkQ98kmxDpWLQz8UIeadNm/2b2mIweA0=,tag:lUcvkNw2hW9cupQT7ybhSw==,type:str]
    pgp: []
    encrypted_regex: ^(value)$
    version: 3.7.1
