kind: ConfigMap
apiVersion: v1
metadata:
  name: cd-cm
data:
  payload.json: |
    {
      "resourceKind": "WorkflowTemplate",
      "resourceName": "cd",
      "namespace": "argo-workflows",
      "submitOptions": {
        "generateName": "cd-",
        "labels": "workflows.argoproj.io/workflow-template=cd",
        "parameters": [
          "environment=dev",
          "domain=galaxy-dev.io",
          "image-tag=stargate-3620-g8d3b6724b",
          "git-sha=8d3b6724b1395c8f8960b92df5ba5e1354a877b2"
        ]
      }
    }
