apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ego-dispatcher
  namespace: deploy
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: galaxy-dev-notify
    notifications.argoproj.io/subscribe.on-sync-failed.slack: galaxy-dev-notify
    notifications.argoproj.io/subscribe.on-sync-running.slack: galaxy-dev-notify
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ego-deploy
  source:
    repoURL: https://github.com/starburstdata/stargate.git
    targetRevision: TEST_SHA
    path: charts/dispatch
    helm:
      parameters:
        - name: image.tag
          value: TEST_TAG
        - name: deployment.region
          value: us-east-1
      valueFiles:
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-dispatcher/dev/_base/values.yml?uniq=f486acfd-f87f-4b0f-9e9a-8c00c7ea7819
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-dispatcher/dev/_base/secrets/db.yml?uniq=9186EAD0-C35C-4801-B7AE-A0FF15BCD93E
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-dispatcher/dev/_base/secrets/dispatch.yml?uniq=9186EAD0-C35C-4801-B7AE-A0FF15BCD93E
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-dispatcher/dev/_base/secrets/login.yml?uniq=9186EAD0-C35C-4801-B7AE-A0FF15BCD93E
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-dispatcher/dev/us-east-1/_base/values.yml?uniq=51B9CF53-EC28-4311-8070-8C4F24ED655B
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-dispatcher/dev/us-east-1/_base/config-properties.yml?uniq=5CB6826F-27ED-423B-BDAF-48606C9EF57F
        - secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/starburstdata/ego-ops/main/ego-dispatcher/dev/us-east-1/_base/log-properties.yml?uniq=51B9CF53-EC28-4311-8070-8C4F24ED655B
  destination:
    name: control-plane
    namespace: ego-dispatcher
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
