apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: query-history-segment-loader
    namespace: deploy
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    project: ego-deploy
    source:
        repoURL: https://github.com/starburstdata/stargate.git
        targetRevision: TEST_SHA
        path: charts/query-history-segment-loader
        helm:
            parameters:
                - name: imageTag
                  value: ENC[AES256_GCM,data:7a8+YUp79Go=,iv:TN8DuE3kwMaSd9QOF7wA4ysXKwE/TqKI7r798uKMQ5w=,tag:DuNVgZG2T4UEhAEw7e0uBw==,type:str]
                - name: localDevelopment
                  value: ENC[AES256_GCM,data:hUAlw4c=,iv:nw862o1EW34zHF/c1RL0B7fcOAfTBXU2vbCgUgB0DUs=,tag:JQ71V+UYIdB6OgaP9dnNzg==,type:str]
                - name: kafka.bootstrap.servers
                  value: ENC[AES256_GCM,data:juW0Oww7g3bTKA6U7BuYg+ES2xn7W41bblN38yPxKDVRBZhqSlEI4hlJ3oY=,iv:D2yeT4QumC4h6t31/NDZjsJC+yg189BBz9lmdPFMvPk=,tag:e2KWXYvKJaFBbbYzaf7G8A==,type:str]
                - name: kafka.sasl.username
                  value: ENC[AES256_GCM,data:Z5pugMwOdlgI8hIXAgFCgw==,iv:GLEJTGn7EfYuj1iEPJ9bFliR7npYawOeeZiVmhLbLGI=,tag:WmzIKBSRnciFB2A9d58tLQ==,type:str]
                - name: kafka.sasl.password
                  value: ENC[AES256_GCM,data:WuxWwuBwTzkKvLMYx5v/Dum86KHQXx8TcCnb0IibY/QwOl8EpCjHHeDZWzdcAbaR7fbNukHd/oxHAnzssuSCcQ==,iv:/AQBkDq6G//T9oNR1sWvQzxckh/s1URcwZMHYGLNh5M=,tag:bzMgUvFtcm85YkYK4K0/kQ==,type:str]
                - name: segment.apiKey
                  value: ENC[AES256_GCM,data:S4rSlE+ZkdKs7FI8FtYqdXUQSAQAcKkFF4Dzc3FLims=,iv:DFXfUWkRTUhJTrtXjctILGeUo56l5/jlTZf/Av4OAxo=,tag:Xt+geEC/AH4sxoBieL69vw==,type:str]
            valueFiles:
                - ./values.yaml
    destination:
        name: control-plane
        namespace: query-history-segment-loader
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:662260526581:key/3f226811-712c-49d1-a5b7-de59223ec1cb
          created_at: "2022-07-14T21:39:43Z"
          enc: AQICAHg1QZDATeVp971NNJF8tQQgf93gP0h0ctR/hGudQ4wAMQG/oGMi20Y4mNhHmWXz2znIAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMFoTBMpVfn1ZRepgMAgEQgDuMYJHrThTwCiar325Kqe5QTjq7wNfP7Dgczx5MZcYxs5DXNDRlJxWFdCSUBJSlOmPUEHy/UCWK0XBEZA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-14T21:39:43Z"
    mac: ENC[AES256_GCM,data:rFydhEZtTAUcRC0RMUuL//GaRRz96E8irJ6rRE6Du8oTXrlWA7j8a1FfwNqf8muuNVLiFbkGzNSZSPeI3QC3JvGYTkTkmNvHkOFHHlS8Dx5AS6OrgYJHQocaLE1rkvg8GzjUBsT4HAJ1QSlVnNeXwtE5n11/OEIy97g3KBMMw4c=,iv:1w/CN+7rL48C1MlV5XAFE8zQTJGu6PLeIzFuHjtu2+0=,tag:uxT+eHWiA/syfwF7xzd0ww==,type:str]
    pgp: []
    encrypted_regex: ^(value)$
    version: 3.7.1
