apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: query-history-segment-loader
    namespace: deploy
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    project: ego-deploy
    source:
        repoURL: https://github.com/starburstdata/stargate.git
        targetRevision: TEST_SHA
        path: charts/query-history-segment-loader
        helm:
            parameters:
                - name: imageTag
                  value: ENC[AES256_GCM,data:+w9yNOax+Ls=,iv:pNNgHleesb/AxhSTF34YZ3npU5jVGathkrGfOsza0jU=,tag:UhGTYU9wJxbOnMmkugoS6Q==,type:str]
                - name: localDevelopment
                  value: ENC[AES256_GCM,data:nCTRqG0=,iv:FcfcX/yTEq23/okNwAnBY8pU9+0GgN+nzqmqRXu0Bic=,tag:YwbKWkb2VPOd00Mos+4qIw==,type:str]
                - name: kafka.bootstrap.servers
                  value: ENC[AES256_GCM,data:dglckSmHwBtP/KQVJxEvHzR6BVHgqamwPpKEDEV4T5l0TTJLGf9Fchcf5o4=,iv:hlwnrtEKD9Bvf+VejJ49PdAiFQ5oupuh0I1no42TdHs=,tag:LAN3tsVQkF1KBWKKnoJbPQ==,type:str]
                - name: kafka.sasl.username
                  value: ENC[AES256_GCM,data:fwfl2EH8Hu2j02ww0CNumA==,iv:M5Y9s7bQ01qX8PsBTUd+ZgLMWn9gGJvDAG979N9Xdao=,tag:vjtGdLJ/iibM4k45Z6RGYA==,type:str]
                - name: kafka.sasl.password
                  value: ENC[AES256_GCM,data:FCUyrodBsk9YJCrq+3XJLDeYgv6wTC/rfzf4YezlOS1VhXvmGjBSrSPEU8O/wW4D3Jv7NUIy331BBJn5PQ5FNA==,iv:Zd+HYmSdrqLIhsrffhQGmWEGHu/HwvZXBOVVKanYbqI=,tag:iYV6dKp3tWoqQNZJ1N2xVg==,type:str]
                - name: segment.apiKey
                  value: ENC[AES256_GCM,data:/6IfDg9qyF0hzKXOmUc2qgontOBJ/vXOizoNF4/vjaU=,iv:4BOT8lL+mtW64nUECiNyhHNBQ4pOFPuZtUYCz3PYrKg=,tag:f7cxZHWHezPHiVHC+yQDgg==,type:str]
            valueFiles:
                - ./values.yaml
    destination:
        name: control-plane
        namespace: query-history-segment-loader
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:662260526581:key/3f226811-712c-49d1-a5b7-de59223ec1cb
          created_at: "2022-07-15T14:26:57Z"
          enc: AQICAHg1QZDATeVp971NNJF8tQQgf93gP0h0ctR/hGudQ4wAMQGN8mqfXqGVtopaHyiPXK21AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMqu87ZUefDuFxZsX1AgEQgDvYMKbQYJJAVUUBfw968PwOsmGQvzPAPqgAUhvRjhAXqt+s4XhDndzacs5dTPRGTGVdBfqvXOtTH+f+Ow==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-15T14:26:57Z"
    mac: ENC[AES256_GCM,data:s6NBXOpxvDMZqK6M/iCNZgp5jAM6inH1Z1w5Aq84QCyJSBaWeSZADC6/GbffXo0EOGrBUx+aEM1ZurOFSvLB/nYdoQsMFepnRyjc/OgAEx5ZIanP4+4L/7CAT1RdjxnSnn9CiD92GHz1Y+SCDXU8Iv3FX+BrfxChgWp0fRSDoYc=,iv:Kmj2vjw1YLricChMOeEByqaAgDl51i6lI6erHjdgh0g=,tag:4EVR3/IUNjaajCLbkPB+hw==,type:str]
    pgp: []
    encrypted_regex: ^(value)$
    version: 3.7.1
