apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: query-history-segment-loader
    namespace: deploy
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    project: ego-deploy
    source:
        repoURL: https://github.com/starburstdata/stargate.git
        targetRevision: TEST_SHA
        path: charts/query-history-segment-loader
        helm:
            parameters:
                - name: imageTag
                  value: ENC[AES256_GCM,data:LHgTeGkRwio=,iv:NrFlqktAECz01HkninW7CBuTXYyQ03dbgqUfVpQ0D0I=,tag:6XUObeE+MI1LG1rHAYSqdw==,type:str]
                - name: localDevelopment
                  value: ENC[AES256_GCM,data:Xbv+qi8=,iv:HHtLp/j4yHwspHnaBectadr9+4CBO+XYlh3lYjOejDU=,tag:yfKjPW0hlMH4sK+bqZnBaA==,type:str]
                - name: kafka.bootstrap.servers
                  value: ENC[AES256_GCM,data:XtXJS8SL2gPa/5BdpFr6+MLLhx+1BbW9RrAdI/RHt+UWKi+dFBxn0ehiPsU=,iv:lnK61SpdPuk9DE4hx1wgyhniOaCSYl+Se9TqzaqTgcE=,tag:9L3TDK43lBprWzoR39W3yA==,type:str]
                - name: kafka.sasl.username
                  value: ENC[AES256_GCM,data:jDdS5yUZ/7lE1bZfAO+mWg==,iv:P8iw14YrHDitsSdCDrJMmB1aY4wKMqOCucvvf19t8gA=,tag:GhUqHMW8GzGsEpaFkl6BKQ==,type:str]
                - name: kafka.sasl.password
                  value: ENC[AES256_GCM,data:ZX3C3rvoBpKkqSPPYrIhTHDrWb2KA7oR03WCsg3aBb0jWt1ODDQgHfpGm4rOX4Bq31nXD+wcbtNuyRt/uI0SiQ==,iv:Rg24VnNotYvISrl5G3DMS5Rb5C295dmi41XFFeh4lD4=,tag:GGonDRAF8sS9XVj1ocHwHw==,type:str]
                - name: segment.apiKey
                  value: ENC[AES256_GCM,data:1dUInPS6r6Rn4L+Vb49q/AQzbJc2sn4seyeuKAqR7DU=,iv:mtSHPIq9szbNL8CRe+OC96YAhnDt23x8Xcis6fJt9LU=,tag:7oDVRjKhDEdcgfiPG0wyww==,type:str]
            valueFiles:
                - ./values.yaml
    destination:
        name: control-plane
        namespace: query-history-segment-loader
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:662260526581:key/3f226811-712c-49d1-a5b7-de59223ec1cb
          created_at: "2022-07-15T15:03:19Z"
          enc: AQICAHg1QZDATeVp971NNJF8tQQgf93gP0h0ctR/hGudQ4wAMQHz9W9gGuOO/QfgU712F9uxAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM6BPMoRSeNEwIjtLaAgEQgDujXWLoNSIYz2DSlszFdCWKs87tSyiJdnDphmNY9EEag4Fv/gfJr/TRu/CO3KKKlmHzaSvLVKLALaUTRw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-15T15:03:19Z"
    mac: ENC[AES256_GCM,data:HhEXvIR29HrJGlzTo8d5agSslhcPIpJ1qak2gCdvNs7hwwFaQD0wRp7oiXeSnwrlJXOTbrn9rcnC7PKtsYkIN/LerRafdY0tcmRj4k/PAJnI08hth5EhZzsjmZaIEkdiv8YEcUXWILtHXaFLVsH+ekHC4mcWeoau/hZWmMq0mBQ=,iv:lgIUTkxeJNzKX3Q87bKv+Iz8Yyianj988RzIce4GCLM=,tag:ah6Th3MvUfpIy+DKbUaM1A==,type:str]
    pgp: []
    encrypted_regex: ^(value)$
    version: 3.7.1
