apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: query-history-segment-loader
    namespace: deploy
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    project: ego-deploy
    source:
        repoURL: https://github.com/starburstdata/stargate.git
        targetRevision: TEST_SHA
        path: charts/query-history-segment-loader
        helm:
            parameters:
                - name: imageTag
                  value: ENC[AES256_GCM,data:O1teTHkKr6s=,iv:ltMK5PDy3rUWRqIzYCJ144Fu89iTCDjceilVbOjsX5g=,tag:G6fyDwZ1lYx7FqUGX3m1/w==,type:str]
                - name: localDevelopment
                  value: ENC[AES256_GCM,data:FCbVl3I=,iv:sFNHxdDBi7oMPVBM7dQuz8ZU5oyq+9JDo+o9QhvL4vk=,tag:0ti8FkJenjNiAsX/FopNNQ==,type:str]
                - name: kafka.bootstrap.servers
                  value: ENC[AES256_GCM,data:fOdky2pfPcLsABWHfygQTD0uoTTuzScQewEnoR6RAusAPi+xqQFpt2Fp4tg=,iv:5f9TB2JHTqTyYWmczPY6g9qOsg0VchupeenqCGHT108=,tag:+jvMbbrIBzLU5RyoM9nAAQ==,type:str]
                - name: kafka.sasl.username
                  value: ENC[AES256_GCM,data:vWqUr9qndtiOnpViLGvrcA==,iv:EdbjORFejcNnIfGtbEWsiwiDbzWSIjF5VyemkQ3bAiA=,tag:YNGIo1eahiG/wO+tBckZIw==,type:str]
                - name: kafka.sasl.password
                  value: ENC[AES256_GCM,data:MVMJzyv26/+MfVKsJdvALpUIIHMnOPgI2UjVmhrqhXDQL1dRmW860h8UvaQNqTYjSJdJx6tsRh0PObG7C8g1Ew==,iv:CdAHtwPpDZw0RZhAq0igYrkzKkzkieKdFAafHRUHFu0=,tag:g9MWrGFOMuJIs9QUoPYymQ==,type:str]
                - name: segment.apiKey
                  value: ENC[AES256_GCM,data:L3L8v9wL4NYhwRIE/ygJpzGcxRNS5V5fwK+SvJCHRMo=,iv:HpHS8NTkWkTUwFzElMagxmuZ8vWme50pZ09R4xk1yzA=,tag:nCiiCa5Z8eNhtrL8y19KpA==,type:str]
            valueFiles:
                - ./values.yaml
    destination:
        name: control-plane
        namespace: query-history-segment-loader
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:662260526581:key/3f226811-712c-49d1-a5b7-de59223ec1cb
          created_at: "2022-07-15T16:03:58Z"
          enc: AQICAHg1QZDATeVp971NNJF8tQQgf93gP0h0ctR/hGudQ4wAMQHTjq2xs3nJk4BvlofQZi28AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMqOyL9m8/geULMq1oAgEQgDu0zfa/htAxwA2z4C5Q2WKiwziLEP5gErjE/7U09bPAHlK8PTEAFlwiupq5bkKdMo/JEQHU7U4XPawQ4Q==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-15T16:03:59Z"
    mac: ENC[AES256_GCM,data:qV4PS1Y+986D7nJkHbVet78hAVqor0czu/aD29AnNYzEfPDOjlaGp5GXgPQ9S26HfpaNFFY0Z00BJANEKTzyjQ4mQAnOEBeMEnXBXMMhMarmRjtSAiFiPYr7bMU/xvWdrSsCEgJeWOLu+8CtyvRxStcciBLgNQAsg/8qlNKbNS0=,iv:U5rG+tEMV3ynIMdI/QddHd73X3ozhITXZN+veuDamiw=,tag:4eWFMsmfe8BhqysPzAodEg==,type:str]
    pgp: []
    encrypted_regex: ^(value)$
    version: 3.7.1
