apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: query-history-segment-loader
    namespace: deploy
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    project: ego-deploy
    source:
        repoURL: https://github.com/starburstdata/stargate.git
        targetRevision: TEST_SHA
        path: charts/query-history-segment-loader
        helm:
            parameters:
                - name: imageTag
                  value: ENC[AES256_GCM,data:l2o2o+/XUqA=,iv:JPbKcVsTB26oaXvZhbkl0NQu77wnYKCfF3D732tw7JE=,tag:xFPc2MQ7VI9MecwZ+4DIlw==,type:str]
                - name: localDevelopment
                  value: ENC[AES256_GCM,data:FFMZffs=,iv:5NUVSX151A2+QHFTTv7wdZxOq8Pmr+EZJBAFz2iGokc=,tag:ZM75BLm3Ill8bWLIEF6+Wg==,type:str]
                - name: kafka.bootstrap.servers
                  value: ENC[AES256_GCM,data:BeVeps7SI52h3HP0mblJyrphPB9zu8DIBmGUJvQlfIUKi9Xm574r1tIVxWc=,iv:L10ZW5bFEq4RQWFeejyZdIl3ZohL9IGGy7bSoVny0sk=,tag:HarNUxAagav2uCa4rSsQMQ==,type:str]
                - name: kafka.sasl.username
                  value: ENC[AES256_GCM,data:L1JOm05RNF5hWHM0k9PoRw==,iv:qVBbzN03T11k4JV2QdF0/BX/ItOdBGEIT+cUJ5O4iWE=,tag:7HAKdUW7QkQrAIhCJuZ1nA==,type:str]
                - name: kafka.sasl.password
                  value: ENC[AES256_GCM,data:+5tnoRNm3n/EgL5c8Uo+UtOQdcFttuffWDmoFqlghoBqJS+huAex3InGRXxD00GULngdjiwQ1FtgISpZkqMCHA==,iv:339n1I+KcVpm6jyjQMDxUeP7BfYCBLZyHprG2WfK+rA=,tag:YWYpUDS5bP5H7OQP9CWx9Q==,type:str]
                - name: segment.apiKey
                  value: ENC[AES256_GCM,data:GMFCorPZPKw9y7Psn3xbbHN7+MmWu/PlgiQJVWTohUM=,iv:BG2tVO41f/MqcwlNV3yozBvHITKjd6mVHZrbw+lL52Q=,tag:xgE3F109lOBK82o+JopDXw==,type:str]
            valueFiles:
                - ./values.yaml
    destination:
        name: control-plane
        namespace: query-history-segment-loader
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:662260526581:key/3f226811-712c-49d1-a5b7-de59223ec1cb
          created_at: "2022-07-15T15:12:10Z"
          enc: AQICAHg1QZDATeVp971NNJF8tQQgf93gP0h0ctR/hGudQ4wAMQH7kzDPOolib20UCzY2zHtQAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMe+I7w5T4P4XTw6ehAgEQgDs4t9ZqIKO1WTshuAz1vwMTO2v1PwPrfvl+SLA1hu+4dEfQsUYhxSzwSlBaiwWDwNI9WAaowYbNCqiWjA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-15T15:12:10Z"
    mac: ENC[AES256_GCM,data:dQ1KLcVTf3QsENZW0moweykvk3sV2jXUn8TyKvYIjuwr3ry0Yo4tJdVNCVanvWgH17KLfe4z/6iMgQNY7gaUriSFh69nTg94CHA5PfQPiCdNibfIiCYSmEUCNzIzLRdbmy+/V0pX2jmc4jRT3J/N17Npb67AkWH3puPIBjrpHbU=,iv:HTF8at2P3K1yDFk3v/3LaxI8SkcMmcfA0egL8hAiaOA=,tag:NFLQPTfQjznw2biiG+/TXw==,type:str]
    pgp: []
    encrypted_regex: ^(value)$
    version: 3.7.1
