apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: query-history-segment-loader
    namespace: deploy
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    project: ego-deploy
    source:
        repoURL: https://github.com/starburstdata/stargate.git
        targetRevision: TEST_SHA
        path: charts/query-history-segment-loader
        helm:
            parameters:
                - name: imageTag
                  value: ENC[AES256_GCM,data:fljbPCSBlJw=,iv:6UfgnGa7wQAypDWZ/O9z9DxZ+cgtTyiLEQAJugp89LI=,tag:w4ztWdJ79JsfuRbtjLTq8A==,type:str]
                - name: localDevelopment
                  value: ENC[AES256_GCM,data:yOxxVus=,iv:qGZwBqxnbR8yrbMyzQgOjXA/A20LYzFFC+ks0DxNHSs=,tag:n9obz7YYeY6ojvNISXuq5Q==,type:str]
                - name: kafka.bootstrap.servers
                  value: ENC[AES256_GCM,data:3Ks1JAuzS6XJUCs51J4LfVX638y1KXImEnKj1wXvPDkltS3cjAMPHM4PleA=,iv:CzhkRGtttNeLisecqlMw+Abocsj09jjKjmUZWU/GHas=,tag:uv2GmLpGxPf7AYJ/71Hb8Q==,type:str]
                - name: kafka.sasl.username
                  value: ENC[AES256_GCM,data:MGcgQKId91QdcJUWq76jYA==,iv:tOKZ+YkY30k+Cqv9j+0iV7DcKozKeR2DqH3AVAWL5uk=,tag:NCYebqNHYUayEMJAz5t8Jw==,type:str]
                - name: kafka.sasl.password
                  value: ENC[AES256_GCM,data:FOtewHHzUpzcdMARMx+6nUpAEqpb7mst8aTmGqPS2An613usBkxIGEjFp4uVYEZkzekuw8iiNT5W7sh2PjHbgw==,iv:lxORpVso7uoyH2oqpeoJNNeW6hMA4vkJ8F1bm6SYXc8=,tag:8c4KDq0Jl9cTM5p3TY/nug==,type:str]
                - name: segment.apiKey
                  value: ENC[AES256_GCM,data:mKjxFaK+stfgPp5I53aUIb9WV35b4bPF08rF//G4p9Y=,iv:gLXGfSlDwEPLk/EaPav4sVl/KvKF2RI6e9MRI426uOk=,tag:oS5EjKbLsy4xb1ZXp9FWFQ==,type:str]
            valueFiles:
                - ./values.yaml
    destination:
        name: control-plane
        namespace: query-history-segment-loader
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:662260526581:key/3f226811-712c-49d1-a5b7-de59223ec1cb
          created_at: "2022-07-15T14:34:47Z"
          enc: AQICAHg1QZDATeVp971NNJF8tQQgf93gP0h0ctR/hGudQ4wAMQGXLHhFWUD0bOED2RlFX62dAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMtB3+HK+0jiuOO8FpAgEQgDs7qfe6u7ot2P/nZI9eAgbyS+QnQMCf0bVdbTfk8dKiKpZ5VD1wZwqPSkoh6erYvAIMhZr4LW0IP0JVkw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-15T14:34:47Z"
    mac: ENC[AES256_GCM,data:XLq6npKdpr9b3SLBchy99PRTTCW9QvDWs4EwKzLOnvVHJ4uJRIHrgU5wRj9WG5y1oitejbDfu544af1wIeWHbXANEbeWF1volxsFlKbA6gKmnCSXojWidWctubple4Nhg4cvOhZXw8+DD9GGrrd8ZdKyEBdhCACNkXGR+UJUztQ=,iv:l0CJ96Ag3xB0q1YqRibjA2cjN0vwodP5fjHOxEtTznc=,tag:mp7FzFodXmwh9nFKFzkLIw==,type:str]
    pgp: []
    encrypted_regex: ^(value)$
    version: 3.7.1
