apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: query-history-segment-loader
    namespace: deploy
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    project: ego-deploy
    source:
        repoURL: https://github.com/starburstdata/stargate.git
        targetRevision: TEST_SHA
        path: charts/query-history-segment-loader
        helm:
            parameters:
                - name: imageTag
                  value: ENC[AES256_GCM,data:7bHpwJL54/A=,iv:QgZrlQSWEmB3tX1YaaC6v15b7HLZL96ztPJnBjy5/QA=,tag:b9PYeTjszQX+okIL3RdzwA==,type:str]
                - name: localDevelopment
                  value: ENC[AES256_GCM,data:cD5ndwA=,iv:bTbg18vsGPuxid/GVKknkjN0gGz5nwI7om68FRXJ6B8=,tag:mDleBVbKFTPzceb7efMmSQ==,type:str]
                - name: kafka.bootstrap.servers
                  value: ENC[AES256_GCM,data:qI8DueOWCghZFt3WkRFYTcXP17C1q3Gp70nyny+vshHNd54kuZh3KgaeDdc=,iv:iC0lL8eCKL0ZDf3fUGbZ2YPWC3UrR2FT4TpCB6JSarw=,tag:gcgovQPqhut2OVt8JwDlAQ==,type:str]
                - name: kafka.sasl.username
                  value: ENC[AES256_GCM,data:JZfWBA5QgGrfRD87Hp0lGA==,iv:iKhlsmdBn+XTzHtU1+DqFYB7MmdSVGQQxVMaGA14G88=,tag:9y4xF44FV8uT6JrPtqqGPw==,type:str]
                - name: kafka.sasl.password
                  value: ENC[AES256_GCM,data:FkcvjPs37/cX5PttGuzQ6E6PsmhGtB64LbdB5j2xxGJJIzbc0uLMYnsOGzN2z3BDmMiaPvolp39MLuY7rrFEGg==,iv:IVmlj6/7CPLxFYzb54ozBItKnBBHuuvwNRhnwrkcxfs=,tag:Z9C1FZay3U1Gcpavfe9NEQ==,type:str]
                - name: segment.apiKey
                  value: ENC[AES256_GCM,data:fxyhQsTiq6EY+p3cRsOmQ6gxIiQBKsPb+7Ysndcqgxs=,iv:5sjKcjXrqLbax2+8QtUy8xqeTWlHlQ6WPOE1CR4uNHc=,tag:Id+X0aGQkPuZchZusXrdfg==,type:str]
            valueFiles:
                - ./values.yaml
    destination:
        name: control-plane
        namespace: query-history-segment-loader
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:662260526581:key/3f226811-712c-49d1-a5b7-de59223ec1cb
          created_at: "2022-07-14T21:12:40Z"
          enc: AQICAHg1QZDATeVp971NNJF8tQQgf93gP0h0ctR/hGudQ4wAMQEMOMP1EupZjNb4USsiMqELAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM2K0rK/HEqWGLpZXsAgEQgDvl8/YwLVRMtCrXyUuc4ogUSYVFLtEf/uLI2O0wij5oMONLfaIzgMBjcT8JyVO/R97mZ1zRuEXK85qUQw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-14T21:12:40Z"
    mac: ENC[AES256_GCM,data:ldn0+1JFaRdWk5Eg/UGE+2cxV2v2eI11e8JiPFQHxi6+upJU4Cv6vPHe435bklY3aXIEcRtDaOJH75n+bguUiSpGQtC2Gpxq+a4QMsVqR6nvz/sJFwSilL8A03DvPTbsmTWZViIIF8V0nuRjMNkKQdnUgyQEie7DU9Xgjq7T0kc=,iv:cC9Y2K1q/AXOLwAcn/ytODnkfvmUN8OOEQF1stwMWI8=,tag:blx2vdOZTIJQFFc/4fGWGw==,type:str]
    pgp: []
    encrypted_regex: ^(value)$
    version: 3.7.1
