apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: query-history-segment-loader
    namespace: deploy
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    project: ego-deploy
    source:
        repoURL: https://github.com/starburstdata/stargate.git
        targetRevision: TEST_SHA
        path: charts/query-history-segment-loader
        helm:
            parameters:
                - name: imageTag
                  value: ENC[AES256_GCM,data:lpGf7IKzbcw=,iv:2H+IO3rMAiSueYBNlRSlcWopwo2dwFBCAp1TYbyLGOY=,tag:v6AenscBtPo04KnVXtLhZA==,type:str]
                - name: localDevelopment
                  value: ENC[AES256_GCM,data:72jnZwo=,iv:ACpLEYfvgZlCkvfb6npvZYXBT/j5NG1ziphhCjA7NkA=,tag:nGuwLIu2KIC28/GNbDAnbA==,type:str]
                - name: kafka.bootstrap.servers
                  value: ENC[AES256_GCM,data:aZsRPnDWmcDAMUGI9nS4y6j0fBp/mw6PrHy+tlG9LNTzKQvODGpi6XI/RYM=,iv:NhC7ozTXXaXDz9mdLqusnXDh/+1S+jdhaJrCYDWS7+g=,tag:sG5u8b6a8dTh2BDMbEZJhw==,type:str]
                - name: kafka.sasl.username
                  value: ENC[AES256_GCM,data:Gfe99dgYF6YmHR9Rg+fT1A==,iv:pga2RTKA24DcM9OtOJczgKbeqCpLmuFsZNGxFC1B6jw=,tag:31UGiTMmdC//ww4kIVPcdw==,type:str]
                - name: kafka.sasl.password
                  value: ENC[AES256_GCM,data:XKA9TmoUjyO0YOUc1ULBQRkYujQs5+BnBWayPikqNHM3sP4UfNOzwrmIZAcO6l5KkGzfbb3yY0rEEgOetM5H4A==,iv:yJeneLtHQdH+Jt5HfoDw56QaGEQJIgjP18FZpC75+q4=,tag:yqubH8xh0tFFtzqNP4svSg==,type:str]
                - name: segment.apiKey
                  value: ENC[AES256_GCM,data:hxjjie0HO89h8lIyrqzvWfj987LrkBEcXctSP3wWds0=,iv:QVxcMOVcxlcEXh8IDW+zqNDW478oI88Mw8YxScFYs8k=,tag:mwCGTn51s91JueHpY7m2Xg==,type:str]
            valueFiles:
                - ./values.yaml
    destination:
        name: control-plane
        namespace: query-history-segment-loader
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:662260526581:key/3f226811-712c-49d1-a5b7-de59223ec1cb
          created_at: "2022-07-15T14:55:36Z"
          enc: AQICAHg1QZDATeVp971NNJF8tQQgf93gP0h0ctR/hGudQ4wAMQEoi+islyPJzkc0oxLgISRNAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM8vEFoHNx6TtUTX2/AgEQgDsWJO4fwz2300mpbWApwP1OzIp1g7UGsK4aGEDETO5jfTY6UQ+V3emRYQ99IKsxdo5SRyxADKq/6gPmYg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-15T14:55:36Z"
    mac: ENC[AES256_GCM,data:gb/XR7joWV+dNHOHihOLbcuLtbdyD0WQOpKJ9XaDwJbAaUYGk1UTxd5lhgX1YxCQnCPEdA3T+28Yr5S4M1H52aCiwq+gPWfXsCrWoqCpgPDRxqfaGnOjfwtg95rDQzNzlZuc4aue5w+azACufv24CU9zSGPB081o5QT3rZB7Y0s=,iv:ePUeqfOz4Ni9di0fxhFy+MzceovX2+9KEF+y+eHXpnY=,tag:JAWuN9So53ys3SZT2fIN/g==,type:str]
    pgp: []
    encrypted_regex: ^(value)$
    version: 3.7.1
