name: New workflow dispatch
on:
  workflow_dispatch:
    inputs:
      env:
        required: true
        type: choice
        description: "Env"
        options: 
        - dev
        - demo
        - prod
      sleep-seconds:
        required: true
      flag:
        required: true
        type: boolean
  pull_request:
    types:
      - synchronize


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set env vars
        run: |
          # Set defaults to test with
          if [[ '${{ github.event.inputs }}' == '' ]]; then
            echo "ENV=dev" >> $GITHUB_ENV
            echo "SLEEP_SECONDS=10" >> $GITHUB_ENV
            echo "FLAG=true" >> $GITHUB_ENV
            echo "REF=refs/heads/main" >> $GITHUB_ENV
          else
            echo "ENV=${{ github.event.inputs.env }}" >> $GITHUB_ENV
            echo "SLEEP_SECONDS=${{ github.event.inputs.sleep-seconds }}" >> $GITHUB_ENV
            echo "FLAG=${{ github.event.inputs.flag }}" >> $GITHUB_ENV
            echo "REF=${{ github.event.ref }}" >> $GITHUB_ENV
          fi

      - name: Echo inputs
        run: |
          echo '${{ toJSON(inputs) }}'
          echo '${{ env }}'

      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'

      - name: Sleep before dispatching
        run: sleep 10

      - name: Dispatch sleep workflow to ${{ inputs.env }} environment
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: sleep.yaml
          ref: ${{ env.REF }} # Doesn't actually work with git SHA :(
          inputs: '{ "env": "${{ env.ENV }}", "sleep-seconds": "${{ env.SLEEP_SECONDS }}"}'
