name: Sleep
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      sleep-seconds:
        required: true

jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs
        run: echo '${{ toJSON(inputs) }}'

      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'

      - name: Sleep for ${{ inputs.sleep-seconds }} seconds
        run: sleep ${{ inputs.sleep-seconds }}
