name: Sleep
on:
  workflow_dispatch:
    inputs:
      uuid:
        required: true
      sleep-seconds:
        required: true

jobs:
  sleep:
    name: sleep-${{ inputs.uuid }}
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run: |
          echo "Sleeping for ${{ inputs.sleep-seconds }} seconds"
          sleep_time=${{ inputs.sleep-seconds }}
          sleep ${sleep_time}
          echo "Done sleeping"
          if [[ $((sleep_time%2)) -eq 0 ]]; then exit 0; else exit 1; fi
