name: Sleep
on:
  workflow_dispatch:
    inputs:
      sleep-seconds:
        required: true
      flag:
        required: true
        type: boolean

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs
        run: echo '${{ toJSON(inputs) }}'

      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'

  middle:
    runs-on: ubuntu-latest
    needs: init
    if: ${{ inputs.flag }}
    steps:
      - name: Echo inputs
        run: echo '${{ toJSON(inputs) }}'

  sleep:
    runs-on: ubuntu-latest
    needs: middle
    steps:
      - name: Sleep in for ${{ inputs.sleep-seconds }} seconds
        run: |
          sleep ${{ inputs.sleep-seconds }}
