name: Test Empty Matrix
on:
  workflow_dispatch:
    inputs:
      flag:
        required: true
        type: boolean

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      envs: ${{ steps.gen-matrix.outputs.envs }}
    steps:
      - id: gen-matrix
        name: Generate matrix
        run: |
          if [[ '${{ inputs.flag }}' == 'true' ]]; then
              envs='["dev","demo","prod"]'
          else
              envs='[]'
          fi

          echo $envs
          echo "envs=$envs" >> $GITHUB_OUTPUT

  matrix-run:
    needs: generate-matrix
    if: ${{ needs.generate-matrix.outputs.envs != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJSON(needs.generate-matrix.outputs.envs) }}
    uses: ./.github/workflows/env-sleep.yaml
    with:
      env: ${{ matrix.environment }}
      flag: ${{ inputs.flag }}
      sleep-seconds: 1
