name: Test ego-ops workflow
on:
  repository_dispatch:
    types:
      - update-all
      - update-billing-aggregator
      - update-dispatch
      - update-metastore
      - update-portal

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ toJson(github.event.client_payload.body) }} > payload.json
      - run: cat payload.json
      - name: JSON to variables
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: "payload.json"
          prefix: pl
      - run: printenv
