name: Test dispatch
on:
  workflow_dispatch:
    inputs:
      uuid:
        required: true
      sleep-seconds:
        required: true

jobs:
  test-dispatch:
    runs-on: ubuntu-latest
    steps:
      - id: dispatch-sleep
        name: Dispatch random sleep workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: sleep.yaml
          inputs: '{ "uuid": "${{ inputs.uuid }}", "sleep-seconds": "${{ inputs.sleep-seconds }}"}'
