name: Test ego-ops workflow
on:
  repository_dispatch:
    types:
      - update-all
      - update-billing-aggregator
      - update-dispatch
      - update-metastore
      - update-portal

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      CONTAINER_NAME: ego-ops-update-image-tags
      CONTAINER_TAG: test
    outputs:
      pull-request-number: ${{ steps.run-update-image-tags-container.outputs.pull-request-number }}
    steps:
      - run: echo ${{ toJson(github.event.client_payload.body) }} > payload.json
      - name: JSON to variables
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: "payload.json"
          prefix: pl

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-2

      - name: Login to the ECR Docker Registry
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr
        with:
          registries: 662260526581

      - name: Run container to update image tags
        id: run-update-image-tags-container
        run: |
          docker run --rm \
          -e AUTO_MERGE="${{ env.pl_autoMerge }}" \
          -e CLUSTER="${{ env.pl_cluster }}" \
          -e DEST_BRANCH="${{ env.pl_mergeToBranch }}" \
          -e ENVIRONMENT="${{ env.pl_environment }}" \
          -e GIT_SHA="${{ env.pl_gitSha }}" \
          -e GITHUB_ACTION="${{ github.event.action }}" \
          -e IMAGE_TAG="${{ env.pl_imageTag }}" \
          -e AWS_ACCESS_KEY -e AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN \
          -e GITHUB_REPOSITORY -e GITHUB_TOKEN \
          662260526581.dkr.ecr.us-east-2.amazonaws.com/${{ env.CONTAINER_NAME }}:${{ env.CONTAINER_TAG }}
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}

  use-pr-number:
    runs-on: ubuntu-latest
    needs: update
    steps:
      - run: echo ${{ needs.update.outputs.pull-request-number }}
