name: Test Matrix sleep
on:
  workflow_dispatch:
    inputs:
  pull_request:

jobs:
  run-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        type: ["foo-type", "bar-type"]
    steps:
      - name: Echo inputs
        run: echo '${{ toJSON(inputs) }}'

      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'

      - name: Dump job context
        run: echo '${{ toJSON(job) }}'

      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'

      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'

      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'

      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'

      - name: Echo branch
        run: echo ${{ github.head_ref || github.ref_name }}
