name: Test dispatch
on:
  workflow_dispatch:
    inputs:
      env:
        required: true
      sleep-seconds:
        required: true

jobs:
  test-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs
        run: echo '${{ toJSON(inputs) }}'

      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'

      - name: Dump gith SHA 
        run: |
          echo '${{ github.event.sha }}'
          echo '${{ github.sha }}'

      - name: Sleep before dispatching
        run: sleep 20

      - name: Dispatch sleep workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: sleep.yaml
          ref: ${{ github.sha }}
          inputs: '{ "env": "${{ inputs.env }}", "sleep-seconds": "${{ inputs.sleep-seconds }}"}'
