name: Test dispatch
on:
  workflow_dispatch:
    inputs:
      env:
        required: true
        type: choice
        description: "Env"
        options: 
        - dev
        - demo
        - prod
      sleep-seconds:
        required: true
      flag:
        required: true
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.env }}-${{ github.event.inputs.flag }}

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs
        run: echo '${{ toJSON(inputs) }}'

      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'

      - name: Sleep for ${{ inputs.sleep-seconds }} seconds
        run: sleep ${{ inputs.sleep-seconds }}

  dispatch:
    runs-on: ubuntu-latest
    needs:
      - init
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.inputs.env }}
    steps:
      - name: Echo inputs
        run: echo '${{ toJSON(inputs) }}'

      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'

      - name: Echo if flag and non-zero seconds
        if: ${{ inputs.flag && inputs.sleep-seconds > 0 }}
        run: echo "Flag set and non-zero seconds"

      - name: Echo if not flag and zero seconds
        if: ${{ inputs.sleep-seconds == 0 && ! inputs.flag }}
        run: echo "Flag not set and 0 seconds"

      - name: Sleep before dispatching
        run: |
          sleep ${{ inputs.sleep-seconds }} 
          if [[ '${{ inputs.flag }}' == 'true' ]]; then
            echo "FLAG"
          fi

      #- name: Dispatch sleep workflow to ${{ inputs.env }} environment
      #  uses: benc-uk/workflow-dispatch@v1
      #  with:
      #    workflow: env-sleep.yaml
      #    ref: ${{ github.event.ref }} # Doesn't actually work with git SHA :(
      #    inputs: '{ "env": "${{ inputs.env }}", "sleep-seconds": "${{ inputs.sleep-seconds }}"}'
