name: Test dispatch
on:
  workflow_dispatch:
    inputs:
      val-one:
        required: true
      val-two:
        required: true

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs
        run: echo '${{ toJSON(inputs) }}'

      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
