name: Test GH script
on:
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - name: Echo inputs
      run: echo '${{ toJSON(inputs) }}'

    - name: Dump GitHub context
      run: echo '${{ toJSON(github) }}'

    - name: Get branch protection for main branch
      id: gh-api-script
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GH_SCRIPT_TOKEN }}
        result-encoding: string
        script: |
          const res = await github.rest.repos.getBranchProtection({
            owner: context.repo.owner,
            repo: context.repo.repo,
            branch: 'main'
          });
          console.log(`Res: ${JSON.stringify(res, null, 2)}`);

          const branchProtections = res.data;
          console.log(`Branch protections: ${JSON.stringify(branchProtections, null, 2)}`);

          const lockBranchEnabled = branchProtections.lock_branch.enabled;
          console.log(`Lock_branch enabled: ${lockBranchEnabled}`);

          return lockBranchEnabled;

    - name: Display output
      shell: bash
      run: |
        echo '${{ steps.gh-api-script.outputs.result }}'
