name: Test checkout
on:
  workflow_dispatch:

jobs:
  test-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs
        run: echo '${{ toJSON(inputs) }}'

      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'

      - name: Echo PR labels
        run: echo '${{ toJSON(github.event.pull_request.labels) }}'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ contains(github.event.pull_request.labels.*.name, 'emergency-release') && github.event.pull_request.head.sha || '' }}

      - name: List dir
        run: ls

      - name: Echo foo
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-ci-tests') }}
        run: |
          echo "Foo"
